/* Generated by the Nim Compiler v2.2.4 */
var framePtr = null;
var excHandler = 0;
var lastJSError = null;
var NTI536871312 = {size: 0, kind: 18, base: null, node: null, finalizer: null};
var NTI989855767 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33554466 = {size: 0,kind: 1,base: null,node: null,finalizer: null};
var NTI536871325 = {size: 0, kind: 18, base: null, node: null, finalizer: null};
var NTI536870933 = {size: 0, kind: 18, base: null, node: null, finalizer: null};
var NTI536870932 = {size: 0, kind: 18, base: null, node: null, finalizer: null};
var NTI536870934 = {size: 0, kind: 18, base: null, node: null, finalizer: null};
var NTI536870919 = {size: 0, kind: 16, base: null, node: null, finalizer: null};
var NTI536871001 = {size: 0, kind: 16, base: null, node: null, finalizer: null};
var NTI536871015 = {size: 0, kind: 24, base: null, node: null, finalizer: null};
var NTI33556097 = {size: 0, kind: 24, base: null, node: null, finalizer: null};
var NTI687866351 = {size: 0, kind: 18, base: null, node: null, finalizer: null};
var NTI134217745 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI134217749 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI134217751 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33554435 = {size: 0,kind: 31,base: null,node: null,finalizer: null};
var NTI33555836 = {size: 0, kind: 18, base: null, node: null, finalizer: null};
var NTI33555167 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33555175 = {size: 0, kind: 22, base: null, node: null, finalizer: null};
var NTI33554450 = {size: 0,kind: 29,base: null,node: null,finalizer: null};
var NTI33555174 = {size: 0, kind: 22, base: null, node: null, finalizer: null};
var NTI33555171 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33555172 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI134217741 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI134217743 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33554449 = {size: 0,kind: 28,base: null,node: null,finalizer: null};
var NTI671088643 = {size: 0,kind: 44,base: null,node: null,finalizer: null};
var NTI671088644 = {size: 0, kind: 18, base: null, node: null, finalizer: null};
var NNI671088644 = {kind: 2, len: 2, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "a0", len: 0, typ: NTI671088643, name: "a0", sons: null}, 
{kind: 1, offset: "a1", len: 0, typ: NTI671088643, name: "a1", sons: null}]};
NTI671088644.node = NNI671088644;
var NNI134217743 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217743.node = NNI134217743;
var NNI134217741 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217741.node = NNI134217741;
var NNI33555172 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI33555172.node = NNI33555172;
NTI33555174.base = NTI33555171;
NTI33555175.base = NTI33555171;
var NNI33555171 = {kind: 2, len: 5, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "parent", len: 0, typ: NTI33555174, name: "parent", sons: null}, 
{kind: 1, offset: "name", len: 0, typ: NTI33554450, name: "name", sons: null}, 
{kind: 1, offset: "message", len: 0, typ: NTI33554449, name: "msg", sons: null}, 
{kind: 1, offset: "trace", len: 0, typ: NTI33554449, name: "trace", sons: null}, 
{kind: 1, offset: "up", len: 0, typ: NTI33555175, name: "up", sons: null}]};
NTI33555171.node = NNI33555171;
var NNI33555167 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI33555167.node = NNI33555167;
NTI33555171.base = NTI33555167;
NTI33555172.base = NTI33555171;
NTI134217741.base = NTI33555172;
NTI134217743.base = NTI134217741;
var NNI33555836 = {kind: 2, len: 3, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "Field0", len: 0, typ: NTI33554450, name: "Field0", sons: null}, 
{kind: 1, offset: "Field1", len: 0, typ: NTI33554435, name: "Field1", sons: null}, 
{kind: 1, offset: "Field2", len: 0, typ: NTI33554450, name: "Field2", sons: null}]};
NTI33555836.node = NNI33555836;
var NNI134217751 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217751.node = NNI134217751;
NTI134217751.base = NTI33555172;
var NNI134217749 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217749.node = NNI134217749;
NTI134217749.base = NTI33555172;
var NNI134217745 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217745.node = NNI134217745;
NTI134217745.base = NTI33555172;
var NNI687866351 = {kind: 2, len: 2, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "a", len: 0, typ: NTI33554435, name: "a", sons: null}, 
{kind: 1, offset: "b", len: 0, typ: NTI33554435, name: "b", sons: null}]};
NTI687866351.node = NNI687866351;
NTI33556097.base = NTI33554450;
NTI536871001.base = NTI33554435;
NTI536871015.base = NTI536871001;
NTI536870919.base = NTI33554435;
var NNI536870934 = {kind: 2, len: 4, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "top", len: 0, typ: NTI33554435, name: "top", sons: null}, 
{kind: 1, offset: "right", len: 0, typ: NTI33554435, name: "right", sons: null}, 
{kind: 1, offset: "bottom", len: 0, typ: NTI33554435, name: "bottom", sons: null}, 
{kind: 1, offset: "left", len: 0, typ: NTI33554435, name: "left", sons: null}]};
NTI536870934.node = NNI536870934;
var NNI536870932 = {kind: 2, len: 4, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "x", len: 0, typ: NTI33554435, name: "x", sons: null}, 
{kind: 1, offset: "y", len: 0, typ: NTI33554435, name: "y", sons: null}, 
{kind: 1, offset: "rotate", len: 0, typ: NTI33554435, name: "rotate", sons: null}, 
{kind: 1, offset: "dungeonPieceId", len: 0, typ: NTI33554435, name: "dungeonPieceId", sons: null}]};
NTI536870932.node = NNI536870932;
var NNI536870933 = {kind: 2, len: 6, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "x", len: 0, typ: NTI33554435, name: "x", sons: null}, 
{kind: 1, offset: "y", len: 0, typ: NTI33554435, name: "y", sons: null}, 
{kind: 1, offset: "top", len: 0, typ: NTI33554435, name: "top", sons: null}, 
{kind: 1, offset: "right", len: 0, typ: NTI33554435, name: "right", sons: null}, 
{kind: 1, offset: "bottom", len: 0, typ: NTI33554435, name: "bottom", sons: null}, 
{kind: 1, offset: "left", len: 0, typ: NTI33554435, name: "left", sons: null}]};
NTI536870933.node = NNI536870933;
var NNI536871325 = {kind: 2, len: 2, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "val", len: 0, typ: NTI536870933, name: "val", sons: null}, 
{kind: 1, offset: "has", len: 0, typ: NTI33554466, name: "has", sons: null}]};
NTI536871325.node = NNI536871325;
var NNI989855767 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI989855767.node = NNI989855767;
NTI989855767.base = NTI33555172;
var NNI536871312 = {kind: 2, len: 2, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "val", len: 0, typ: NTI536870933, name: "val", sons: null}, 
{kind: 1, offset: "has", len: 0, typ: NTI33554466, name: "has", sons: null}]};
NTI536871312.node = NNI536871312;
var DefaultRandSeed_671088654 = {a0: 7616934476015405061n, a1: 15122295919272093642n};

function setConstr() {
        var result = {};
    for (var i = 0; i < arguments.length; ++i) {
      var x = arguments[i];
      if (typeof(x) == "object") {
        for (var j = x[0]; j <= x[1]; ++j) {
          result[j] = true;
        }
      } else {
        result[x] = true;
      }
    }
    return result;
  

  
}
var ConstSet1 = setConstr(17, 16, 4, 18, 27, 19, 23, 22, 21);

function nimCopy(dest_p0, src_p1, ti_p2) {
  var result_33557330 = null;

    switch (ti_p2.kind) {
    case 21:
    case 22:
    case 23:
    case 5:
      if (!(isFatPointer__system_u2878(ti_p2))) {
      result_33557330 = src_p1;
      }
      else {
        result_33557330 = [src_p1[0], src_p1[1]];
      }
      
      break;
    case 19:
            if (dest_p0 === null || dest_p0 === undefined) {
        dest_p0 = {};
      }
      else {
        for (var key in dest_p0) { delete dest_p0[key]; }
      }
      for (var key in src_p1) { dest_p0[key] = src_p1[key]; }
      result_33557330 = dest_p0;
    
      break;
    case 18:
    case 17:
      if (!((ti_p2.base == null))) {
      result_33557330 = nimCopy(dest_p0, src_p1, ti_p2.base);
      }
      else {
      if ((ti_p2.kind == 17)) {
      result_33557330 = (dest_p0 === null || dest_p0 === undefined) ? {m_type: ti_p2} : dest_p0;
      }
      else {
        result_33557330 = (dest_p0 === null || dest_p0 === undefined) ? {} : dest_p0;
      }
      }
      nimCopyAux(result_33557330, src_p1, ti_p2.node);
      break;
    case 4:
    case 16:
            if(ArrayBuffer.isView(src_p1)) { 
        if(dest_p0 === null || dest_p0 === undefined || dest_p0.length != src_p1.length) {
          dest_p0 = new src_p1.constructor(src_p1);
        } else {
          dest_p0.set(src_p1, 0);
        }
        result_33557330 = dest_p0;
      } else {
        if (src_p1 === null) {
          result_33557330 = null;
        }
        else {
          if (dest_p0 === null || dest_p0 === undefined || dest_p0.length != src_p1.length) {
            dest_p0 = new Array(src_p1.length);
          }
          result_33557330 = dest_p0;
          for (var i = 0; i < src_p1.length; ++i) {
            result_33557330[i] = nimCopy(result_33557330[i], src_p1[i], ti_p2.base);
          }
        }
      }
    
      break;
    case 24:
    case 27:
            if (src_p1 === null) {
        result_33557330 = null;
      }
      else {
        if (dest_p0 === null || dest_p0 === undefined || dest_p0.length != src_p1.length) {
          dest_p0 = new Array(src_p1.length);
        }
        result_33557330 = dest_p0;
        for (var i = 0; i < src_p1.length; ++i) {
          result_33557330[i] = nimCopy(result_33557330[i], src_p1[i], ti_p2.base);
        }
      }
    
      break;
    case 28:
            if (src_p1 !== null) {
        result_33557330 = src_p1.slice(0);
      }
    
      break;
    default: 
      result_33557330 = src_p1;
      break;
    }

  return result_33557330;

}
                      var helper_671088687 = new BigUint64Array([13739361407582206667n, 15594563132006766882n]);

function mnewString(len_p0) {
        var result = new Array(len_p0);
    for (var i = 0; i < len_p0; i++) {result[i] = 0;}
    return result;
  

  
}

function arrayConstr(len_p0, value_p1, typ_p2) {
        var result = new Array(len_p0);
    for (var i = 0; i < len_p0; ++i) result[i] = nimCopy(null, value_p1, typ_p2);
    return result;
  

  
}

function cstrToNimstr(c_p0) {
      var ln = c_p0.length;
  var result = new Array(ln);
  var r = 0;
  for (var i = 0; i < ln; ++i) {
    var ch = c_p0.charCodeAt(i);

    if (ch < 128) {
      result[r] = ch;
    }
    else {
      if (ch < 2048) {
        result[r] = (ch >> 6) | 192;
      }
      else {
        if (ch < 55296 || ch >= 57344) {
          result[r] = (ch >> 12) | 224;
        }
        else {
            ++i;
            ch = 65536 + (((ch & 1023) << 10) | (c_p0.charCodeAt(i) & 1023));
            result[r] = (ch >> 18) | 240;
            ++r;
            result[r] = ((ch >> 12) & 63) | 128;
        }
        ++r;
        result[r] = ((ch >> 6) & 63) | 128;
      }
      ++r;
      result[r] = (ch & 63) | 128;
    }
    ++r;
  }
  return result;
  

  
}

function isObj(obj_p0, subclass_p1) {
  var result_33557443 = false;

  BeforeRet: {
    var x_33557444 = obj_p0;
    if ((x_33557444 == subclass_p1)) {
    result_33557443 = true;
    break BeforeRet;
    }
    
    Label1: {
        Label2: while (true) {
        if (!!((x_33557444 == subclass_p1))) break Label2;
          if ((x_33557444 == null)) {
          result_33557443 = false;
          break BeforeRet;
          }
          
          x_33557444 = x_33557444.base;
        }
    };
    result_33557443 = true;
    break BeforeRet;
  };

  return result_33557443;

}

function toJSStr(s_p0) {
  var result_33556919 = null;

    var res_33556973 = newSeq__system_u2516((s_p0).length);
    var i_33556974 = 0;
    var j_33556975 = 0;
    Label1: {
        Label2: while (true) {
        if (!(i_33556974 < (s_p0).length)) break Label2;
          var c_33556976 = s_p0[i_33556974];
          if ((c_33556976 < 128)) {
          res_33556973[j_33556975] = String.fromCharCode(c_33556976);
          i_33556974 += 1;
          }
          else {
            var helper_33557002 = newSeq__system_u2516(0);
            Label3: {
                Label4: while (true) {
                if (!true) break Label4;
                  var code_33557003 = c_33556976.toString(16);
                  if ((((code_33557003) == null ? 0 : (code_33557003).length) == 1)) {
                  helper_33557002.push("%0");;
                  }
                  else {
                  helper_33557002.push("%");;
                  }
                  
                  helper_33557002.push(code_33557003);;
                  i_33556974 += 1;
                  if ((((s_p0).length <= i_33556974) || (s_p0[i_33556974] < 128))) {
                  break Label3;
                  }
                  
                  c_33556976 = s_p0[i_33556974];
                }
            };
++excHandler;
            try {
            res_33556973[j_33556975] = decodeURIComponent(helper_33557002.join(""));
--excHandler;
} catch (EXCEPTION) {
 var prevJSError = lastJSError;
 lastJSError = EXCEPTION;
 --excHandler;
            raiseDefect();
            res_33556973[j_33556975] = helper_33557002.join("");
            lastJSError = prevJSError;
            } finally {
            }
          }
          
          j_33556975 += 1;
        }
    };
    if (res_33556973.length < j_33556975) { for (var i = res_33556973.length ; i < j_33556975 ; ++i) res_33556973.push(null); }
               else { res_33556973.length = j_33556975; };
    result_33556919 = res_33556973.join("");

  return result_33556919;

}

function raiseException(e_p0, ename_p1) {
    e_p0.name = ename_p1;
    if ((excHandler == 0)) {
    unhandledException(e_p0);
    }
    
    e_p0.trace = nimCopy(null, rawWriteStackTrace__system_u2180(), NTI33554449);
    throw e_p0;

  
}

function addInt(a_p0, b_p1) {
        var result = a_p0 + b_p1;
    checkOverflowInt(result);
    return result;
  

  
}

function chckRange(i_p0, a_p1, b_p2) {
  var result_33557370 = 0;

  BeforeRet: {
    if (((a_p1 <= i_p0) && (i_p0 <= b_p2))) {
    result_33557370 = i_p0;
    break BeforeRet;
    }
    else {
    raiseRangeError();
    }
    
  };

  return result_33557370;

}

function chckIndx(i_p0, a_p1, b_p2) {
  var result_33557365 = 0;

  BeforeRet: {
    if (((a_p1 <= i_p0) && (i_p0 <= b_p2))) {
    result_33557365 = i_p0;
    break BeforeRet;
    }
    else {
    raiseIndexError(i_p0, a_p1, b_p2);
    }
    
  };

  return result_33557365;

}

function makeNimstrLit(c_p0) {
      var result = [];
  for (var i = 0; i < c_p0.length; ++i) {
    result[i] = c_p0.charCodeAt(i);
  }
  return result;
  

  
}

function subInt(a_p0, b_p1) {
        var result = a_p0 - b_p1;
    checkOverflowInt(result);
    return result;
  

  
}

function mulInt(a_p0, b_p1) {
        var result = a_p0 * b_p1;
    checkOverflowInt(result);
    return result;
  

  
}
var F = {procname: "module algorithm", prev: framePtr, filename: "C:\\Users\\aine\\.choosenim\\toolchains\\nim-2.2.4\\lib\\pure\\algorithm.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module algorithm", prev: framePtr, filename: "C:\\Users\\aine\\.choosenim\\toolchains\\nim-2.2.4\\lib\\pure\\algorithm.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "C:\\Users\\aine\\.choosenim\\toolchains\\nim-2.2.4\\lib\\core\\macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "C:\\Users\\aine\\.choosenim\\toolchains\\nim-2.2.4\\lib\\core\\macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module bitops_utils", prev: framePtr, filename: "C:\\Users\\aine\\.choosenim\\toolchains\\nim-2.2.4\\lib\\std\\private\\bitops_utils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module bitops_utils", prev: framePtr, filename: "C:\\Users\\aine\\.choosenim\\toolchains\\nim-2.2.4\\lib\\std\\private\\bitops_utils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module countbits_impl", prev: framePtr, filename: "C:\\Users\\aine\\.choosenim\\toolchains\\nim-2.2.4\\lib\\system\\countbits_impl.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module countbits_impl", prev: framePtr, filename: "C:\\Users\\aine\\.choosenim\\toolchains\\nim-2.2.4\\lib\\system\\countbits_impl.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module bitops", prev: framePtr, filename: "C:\\Users\\aine\\.choosenim\\toolchains\\nim-2.2.4\\lib\\pure\\bitops.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module bitops", prev: framePtr, filename: "C:\\Users\\aine\\.choosenim\\toolchains\\nim-2.2.4\\lib\\pure\\bitops.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module fenv", prev: framePtr, filename: "C:\\Users\\aine\\.choosenim\\toolchains\\nim-2.2.4\\lib\\pure\\fenv.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module fenv", prev: framePtr, filename: "C:\\Users\\aine\\.choosenim\\toolchains\\nim-2.2.4\\lib\\pure\\fenv.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module math", prev: framePtr, filename: "C:\\Users\\aine\\.choosenim\\toolchains\\nim-2.2.4\\lib\\pure\\math.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module math", prev: framePtr, filename: "C:\\Users\\aine\\.choosenim\\toolchains\\nim-2.2.4\\lib\\pure\\math.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module parseutils", prev: framePtr, filename: "C:\\Users\\aine\\.choosenim\\toolchains\\nim-2.2.4\\lib\\pure\\parseutils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module parseutils", prev: framePtr, filename: "C:\\Users\\aine\\.choosenim\\toolchains\\nim-2.2.4\\lib\\pure\\parseutils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module typetraits", prev: framePtr, filename: "C:\\Users\\aine\\.choosenim\\toolchains\\nim-2.2.4\\lib\\pure\\typetraits.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module typetraits", prev: framePtr, filename: "C:\\Users\\aine\\.choosenim\\toolchains\\nim-2.2.4\\lib\\pure\\typetraits.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module enumutils", prev: framePtr, filename: "C:\\Users\\aine\\.choosenim\\toolchains\\nim-2.2.4\\lib\\std\\enumutils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module enumutils", prev: framePtr, filename: "C:\\Users\\aine\\.choosenim\\toolchains\\nim-2.2.4\\lib\\std\\enumutils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module strbasics", prev: framePtr, filename: "C:\\Users\\aine\\.choosenim\\toolchains\\nim-2.2.4\\lib\\std\\strbasics.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module strbasics", prev: framePtr, filename: "C:\\Users\\aine\\.choosenim\\toolchains\\nim-2.2.4\\lib\\std\\strbasics.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module unicode", prev: framePtr, filename: "C:\\Users\\aine\\.choosenim\\toolchains\\nim-2.2.4\\lib\\pure\\unicode.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module unicode", prev: framePtr, filename: "C:\\Users\\aine\\.choosenim\\toolchains\\nim-2.2.4\\lib\\pure\\unicode.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module strimpl", prev: framePtr, filename: "C:\\Users\\aine\\.choosenim\\toolchains\\nim-2.2.4\\lib\\std\\private\\strimpl.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module strimpl", prev: framePtr, filename: "C:\\Users\\aine\\.choosenim\\toolchains\\nim-2.2.4\\lib\\std\\private\\strimpl.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module strutils", prev: framePtr, filename: "C:\\Users\\aine\\.choosenim\\toolchains\\nim-2.2.4\\lib\\pure\\strutils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module strutils", prev: framePtr, filename: "C:\\Users\\aine\\.choosenim\\toolchains\\nim-2.2.4\\lib\\pure\\strutils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module options", prev: framePtr, filename: "C:\\Users\\aine\\.choosenim\\toolchains\\nim-2.2.4\\lib\\pure\\options.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module options", prev: framePtr, filename: "C:\\Users\\aine\\.choosenim\\toolchains\\nim-2.2.4\\lib\\pure\\options.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jscore", prev: framePtr, filename: "C:\\Users\\aine\\.choosenim\\toolchains\\nim-2.2.4\\lib\\js\\jscore.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jscore", prev: framePtr, filename: "C:\\Users\\aine\\.choosenim\\toolchains\\nim-2.2.4\\lib\\js\\jscore.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module times", prev: framePtr, filename: "C:\\Users\\aine\\.choosenim\\toolchains\\nim-2.2.4\\lib\\pure\\times.nim", line: 0};
framePtr = F;
F.line = 1373;
F.filename = "times.nim";
if (globalThis.utcInstance_838862593 === undefined) {
  globalThis.utcInstance_838862593 = [null];
}
F.line = 1374;
if (globalThis.localInstance_838862594 === undefined) {
  globalThis.localInstance_838862594 = [null];
}
framePtr = F.prev;
var F = {procname: "module times", prev: framePtr, filename: "C:\\Users\\aine\\.choosenim\\toolchains\\nim-2.2.4\\lib\\pure\\times.nim", line: 0};
framePtr = F;
framePtr = F.prev;

function isFatPointer__system_u2878(ti_p0) {
  var result_33557312 = false;

  BeforeRet: {
    result_33557312 = !((ConstSet1[ti_p0.base.kind] != undefined));
    break BeforeRet;
  };

  return result_33557312;

}

function nimCopyAux(dest_p0, src_p1, n_p2) {
    switch (n_p2.kind) {
    case 0:
      break;
    case 1:
            dest_p0[n_p2.offset] = nimCopy(dest_p0[n_p2.offset], src_p1[n_p2.offset], n_p2.typ);
    
      break;
    case 2:
          for (var i = 0; i < n_p2.sons.length; i++) {
      nimCopyAux(dest_p0, src_p1, n_p2.sons[i]);
    }
    
      break;
    case 3:
            dest_p0[n_p2.offset] = nimCopy(dest_p0[n_p2.offset], src_p1[n_p2.offset], n_p2.typ);
      for (var i = 0; i < n_p2.sons.length; ++i) {
        nimCopyAux(dest_p0, src_p1, n_p2.sons[i][1]);
      }
    
      break;
    }

  
}
var F = {procname: "module random", prev: framePtr, filename: "C:\\Users\\aine\\.choosenim\\toolchains\\nim-2.2.4\\lib\\pure\\random.nim", line: 0};
framePtr = F;
F.line = 116;
F.filename = "random.nim";
var state_671088655 = [nimCopy(null, DefaultRandSeed_671088654, NTI671088644)];
framePtr = F.prev;
var F = {procname: "module random", prev: framePtr, filename: "C:\\Users\\aine\\.choosenim\\toolchains\\nim-2.2.4\\lib\\pure\\random.nim", line: 0};
framePtr = F;
framePtr = F.prev;

function toFloat__system_u1572(i_p0) {
  var result_33556006 = 0.0;

  var F = {procname: "system.toFloat", prev: framePtr, filename: "C:\\Users\\aine\\.choosenim\\toolchains\\nim-2.2.4\\lib\\system.nim", line: 0};
  framePtr = F;
    F.line = 1290;
    F.filename = "system.nim";
    result_33556006 = i_p0;
  framePtr = F.prev;

  return result_33556006;

}

function HEX2F__system_u1584(x_p0, y_p1) {
  var result_33556019 = 0.0;

  var F = {procname: "system./", prev: framePtr, filename: "C:\\Users\\aine\\.choosenim\\toolchains\\nim-2.2.4\\lib\\system.nim", line: 0};
  framePtr = F;
    F.line = 1338;
    F.filename = "system.nim";
    result_33556019 = (toFloat__system_u1572(x_p0) / toFloat__system_u1572(y_p1));
  framePtr = F.prev;

  return result_33556019;

}

function epochTime__pureZtimes_u4759() {
  var result_838865560 = 0.0;

  var F = {procname: "times.epochTime", prev: framePtr, filename: "C:\\Users\\aine\\.choosenim\\toolchains\\nim-2.2.4\\lib\\pure\\times.nim", line: 0};
  framePtr = F;
    F.line = 2799;
    F.filename = "times.nim";
    result_838865560 = HEX2F__system_u1584(new Date().getTime(), 1000);
  framePtr = F.prev;

  return result_838865560;

}

function add__system_u1942(x_p0, x_p0_Idx, y_p1) {
          if (x_p0[x_p0_Idx] === null) { x_p0[x_p0_Idx] = []; }
      var off = x_p0[x_p0_Idx].length;
      x_p0[x_p0_Idx].length += y_p1.length;
      for (var i = 0; i < y_p1.length; ++i) {
        x_p0[x_p0_Idx][off+i] = y_p1.charCodeAt(i);
      }
    

  
}

function auxWriteStackTrace__system_u2084(f_p0) {
  var result_33556518 = [[]];

    var it_33556526 = f_p0;
    var i_33556527 = 0;
    var total_33556528 = 0;
    var tempFrames_33556529 = arrayConstr(64, {Field0: null, Field1: 0, Field2: null}, NTI33555836);
    Label1: {
        Label2: while (true) {
        if (!(!((it_33556526 == null)) && (i_33556527 <= 63))) break Label2;
          tempFrames_33556529[i_33556527].Field0 = it_33556526.procname;
          tempFrames_33556529[i_33556527].Field1 = it_33556526.line;
          tempFrames_33556529[i_33556527].Field2 = it_33556526.filename;
          i_33556527 += 1;
          total_33556528 += 1;
          it_33556526 = it_33556526.prev;
        }
    };
    Label3: {
        Label4: while (true) {
        if (!!((it_33556526 == null))) break Label4;
          total_33556528 += 1;
          it_33556526 = it_33556526.prev;
        }
    };
    result_33556518[0] = nimCopy(null, [], NTI33554449);
    if (!((total_33556528 == i_33556527))) {
    result_33556518[0].push.apply(result_33556518[0], [40]);;
    result_33556518[0].push.apply(result_33556518[0], HEX24__systemZdollars_u14((total_33556528 - i_33556527)));;
    result_33556518[0].push.apply(result_33556518[0], [32,99,97,108,108,115,32,111,109,105,116,116,101,100,41,32,46,46,46,10]);;
    }
    
    Label5: {
      var j_33556562 = 0;
      var colontmp__536871688 = 0;
      colontmp__536871688 = (i_33556527 - 1);
      var res_536871690 = colontmp__536871688;
      Label6: {
          Label7: while (true) {
          if (!(0 <= res_536871690)) break Label7;
            j_33556562 = res_536871690;
            result_33556518[0].push.apply(result_33556518[0], cstrToNimstr(tempFrames_33556529[j_33556562].Field2));;
            if ((0 < tempFrames_33556529[j_33556562].Field1)) {
            result_33556518[0].push.apply(result_33556518[0], [40]);;
            addInt__stdZprivateZdigitsutils_u241(result_33556518, 0, tempFrames_33556529[j_33556562].Field1);
            if (false) {
            result_33556518[0].push.apply(result_33556518[0], [44,32]);;
            addInt__stdZprivateZdigitsutils_u241(result_33556518, 0, 0);
            }
            
            result_33556518[0].push.apply(result_33556518[0], [41]);;
            }
            
            result_33556518[0].push.apply(result_33556518[0], [32,97,116,32]);;
            add__system_u1942(result_33556518, 0, tempFrames_33556529[j_33556562].Field0);
            result_33556518[0].push.apply(result_33556518[0], [10]);;
            res_536871690 -= 1;
          }
      };
    };

  return result_33556518[0];

}

function rawWriteStackTrace__system_u2180() {
  var result_33556613 = [];

    if (!((framePtr == null))) {
    result_33556613 = nimCopy(null, ([84,114,97,99,101,98,97,99,107,32,40,109,111,115,116,32,114,101,99,101,110,116,32,99,97,108,108,32,108,97,115,116,41,10]).concat(auxWriteStackTrace__system_u2084(framePtr)), NTI33554449);
    }
    else {
      result_33556613 = nimCopy(null, [78,111,32,115,116,97,99,107,32,116,114,97,99,101,98,97,99,107,32,97,118,97,105,108,97,98,108,101,10], NTI33554449);
    }
    

  return result_33556613;

}

function newSeq__system_u2516(len_p0) {
  var result_33556952 = [];

  var F = {procname: "newSeq.newSeq", prev: framePtr, filename: "C:\\Users\\aine\\.choosenim\\toolchains\\nim-2.2.4\\lib\\system.nim", line: 0};
  framePtr = F;
    F.line = 651;
    F.filename = "system.nim";
    result_33556952 = new Array(len_p0); for (var i = 0 ; i < len_p0 ; ++i) { result_33556952[i] = null; }  framePtr = F.prev;

  return result_33556952;

}

function isNimException__system_u2017() {
    return lastJSError && lastJSError.m_type;

  
}

function getCurrentException() {
  var result_33556452 = null;

    if (isNimException__system_u2017()) {
    result_33556452 = lastJSError;
    }
    

  return result_33556452;

}

function raiseDefect() {
    if (isNimException__system_u2017()) {
    var e_33556664 = getCurrentException();
    if (isObj(e_33556664.m_type, NTI33555172)) {
    if ((excHandler == 0)) {
    unhandledException(e_33556664);
    }
    
    e_33556664.trace = nimCopy(null, rawWriteStackTrace__system_u2180(), NTI33554449);
    throw e_33556664;
    }
    
    }
    

  
}

function unhandledException(e_p0) {
    var buf_33556658 = [[]];
    if (!(((e_p0.message).length == 0))) {
    buf_33556658[0].push.apply(buf_33556658[0], [69,114,114,111,114,58,32,117,110,104,97,110,100,108,101,100,32,101,120,99,101,112,116,105,111,110,58,32]);;
    buf_33556658[0].push.apply(buf_33556658[0], e_p0.message);;
    }
    else {
    buf_33556658[0].push.apply(buf_33556658[0], [69,114,114,111,114,58,32,117,110,104,97,110,100,108,101,100,32,101,120,99,101,112,116,105,111,110]);;
    }
    
    buf_33556658[0].push.apply(buf_33556658[0], [32,91]);;
    add__system_u1942(buf_33556658, 0, e_p0.name);
    buf_33556658[0].push.apply(buf_33556658[0], [93,10]);;
    buf_33556658[0].push.apply(buf_33556658[0], rawWriteStackTrace__system_u2180());;
    var cbuf_33556659 = toJSStr(buf_33556658[0]);
    framePtr = null;
      if (typeof(Error) !== "undefined") {
    throw new Error(cbuf_33556659);
  }
  else {
    throw cbuf_33556659;
  }
  

  
}

function raiseOverflow() {
    raiseException({message: [111,118,101,114,45,32,111,114,32,117,110,100,101,114,102,108,111,119], parent: null, m_type: NTI134217743, name: null, trace: [], up: null}, "OverflowDefect");

  
}

function checkOverflowInt(a_p0) {
        if (a_p0 > 2147483647 || a_p0 < -2147483648) raiseOverflow();
  

  
}

function raiseRangeError() {
    raiseException({message: [118,97,108,117,101,32,111,117,116,32,111,102,32,114,97,110,103,101], parent: null, m_type: NTI134217751, name: null, trace: [], up: null}, "RangeDefect");

  
}

function addChars__stdZprivateZdigitsutils_u202(result_p0, result_p0_Idx, x_p1, start_p2, n_p3) {
    var Temporary1;

  var F = {procname: "addChars.addChars", prev: framePtr, filename: "C:\\Users\\aine\\.choosenim\\toolchains\\nim-2.2.4\\lib\\std\\private\\digitsutils.nim", line: 0};
  framePtr = F;
    F.line = 44;
    F.filename = "digitsutils.nim";
    var old_301990096 = (result_p0[result_p0_Idx]).length;
    F.line = 45;
    if (result_p0[result_p0_Idx].length < (Temporary1 = chckRange(addInt(old_301990096, n_p3), 0, 2147483647), Temporary1)) { for (var i = result_p0[result_p0_Idx].length; i < Temporary1; ++i) result_p0[result_p0_Idx].push(0); }
         else {result_p0[result_p0_Idx].length = Temporary1; };
    Label2: {
      F.line = 47;
      var iHEX60gensym4_301990110 = 0;
      F.line = 128;
      F.filename = "iterators_1.nim";
      var i_536871683 = 0;
      Label3: {
        F.line = 129;
          Label4: while (true) {
          if (!(i_536871683 < n_p3)) break Label4;
            F.line = 50;
            F.filename = "digitsutils.nim";
            iHEX60gensym4_301990110 = i_536871683;
            F.line = 47;
            result_p0[result_p0_Idx][chckIndx(addInt(old_301990096, iHEX60gensym4_301990110), 0, (result_p0[result_p0_Idx]).length - 1)] = x_p1.charCodeAt(chckIndx(addInt(start_p2, iHEX60gensym4_301990110), 0, (x_p1).length - 1));
            F.line = 131;
            F.filename = "iterators_1.nim";
            i_536871683 = addInt(i_536871683, 1);
          }
      };
    };
  framePtr = F.prev;

  
}

function addChars__stdZprivateZdigitsutils_u198(result_p0, result_p0_Idx, x_p1) {
  var F = {procname: "addChars.addChars", prev: framePtr, filename: "C:\\Users\\aine\\.choosenim\\toolchains\\nim-2.2.4\\lib\\std\\private\\digitsutils.nim", line: 0};
  framePtr = F;
    F.line = 56;
    F.filename = "digitsutils.nim";
    addChars__stdZprivateZdigitsutils_u202(result_p0, result_p0_Idx, x_p1, 0, ((x_p1) == null ? 0 : (x_p1).length));
  framePtr = F.prev;

  
}

function addInt__stdZprivateZdigitsutils_u223(result_p0, result_p0_Idx, x_p1) {
  var F = {procname: "digitsutils.addInt", prev: framePtr, filename: "C:\\Users\\aine\\.choosenim\\toolchains\\nim-2.2.4\\lib\\std\\private\\digitsutils.nim", line: 0};
  framePtr = F;
    F.line = 112;
    F.filename = "digitsutils.nim";
    addChars__stdZprivateZdigitsutils_u198(result_p0, result_p0_Idx, ((x_p1) + ""));
  framePtr = F.prev;

  
}

function addInt__stdZprivateZdigitsutils_u241(result_p0, result_p0_Idx, x_p1) {
  var F = {procname: "digitsutils.addInt", prev: framePtr, filename: "C:\\Users\\aine\\.choosenim\\toolchains\\nim-2.2.4\\lib\\std\\private\\digitsutils.nim", line: 0};
  framePtr = F;
    F.line = 116;
    F.filename = "digitsutils.nim";
    addInt__stdZprivateZdigitsutils_u223(result_p0, result_p0_Idx, BigInt(x_p1));
  framePtr = F.prev;

  
}

function HEX24__systemZdollars_u14(xHEX60gensym0_p0) {
  var result_369098768 = [[]];

  var F = {procname: "dollars.$", prev: framePtr, filename: "C:\\Users\\aine\\.choosenim\\toolchains\\nim-2.2.4\\lib\\system\\dollars.nim", line: 0};
  framePtr = F;
    F.line = 20;
    F.filename = "dollars.nim";
    result_369098768[0] = nimCopy(null, [], NTI33554449);
    F.line = 21;
    addInt__stdZprivateZdigitsutils_u241(result_369098768, 0, xHEX60gensym0_p0);
  framePtr = F.prev;

  return result_369098768[0];

}

function raiseIndexError(i_p0, a_p1, b_p2) {
    var Temporary1;

    if ((b_p2 < a_p1)) {
    Temporary1 = [105,110,100,101,120,32,111,117,116,32,111,102,32,98,111,117,110,100,115,44,32,116,104,101,32,99,111,110,116,97,105,110,101,114,32,105,115,32,101,109,112,116,121];
    }
    else {
    Temporary1 = ([105,110,100,101,120,32]).concat(HEX24__systemZdollars_u14(i_p0),[32,110,111,116,32,105,110,32],HEX24__systemZdollars_u14(a_p1),[32,46,46,32],HEX24__systemZdollars_u14(b_p2));
    }
    
    raiseException({message: nimCopy(null, Temporary1, NTI33554449), parent: null, m_type: NTI134217749, name: null, trace: [], up: null}, "IndexDefect");

  
}

function rotl__pureZrandom_u24(x_p0, k_p1) {
  var result_671088667 = 0n;

  var F = {procname: "random.rotl", prev: framePtr, filename: "C:\\Users\\aine\\.choosenim\\toolchains\\nim-2.2.4\\lib\\pure\\random.nim", line: 0};
  framePtr = F;
    F.line = 136;
    F.filename = "random.nim";
    result_671088667 = (BigInt.asUintN(64, x_p0 << BigInt(k_p1)) | (x_p0 >> BigInt(BigInt.asUintN(64, (64n - k_p1)))));
  framePtr = F.prev;

  return result_671088667;

}

function next__pureZrandom_u36(r_p0) {
  var result_671088678 = 0n;

  var F = {procname: "random.next", prev: framePtr, filename: "C:\\Users\\aine\\.choosenim\\toolchains\\nim-2.2.4\\lib\\pure\\random.nim", line: 0};
  framePtr = F;
    F.line = 154;
    F.filename = "random.nim";
    var s0_671088679 = r_p0.a0;
    F.line = 155;
    var s1_671088680 = r_p0.a1;
    F.line = 156;
    result_671088678 = BigInt.asUintN(64, (s0_671088679 + s1_671088680));
    F.line = 157;
    s1_671088680 = (s1_671088680 ^ s0_671088679);
    F.line = 158;
    r_p0.a0 = ((rotl__pureZrandom_u24(s0_671088679, 55n) ^ s1_671088680) ^ BigInt.asUintN(64, s1_671088680 << BigInt(14)));
    F.line = 159;
    r_p0.a1 = rotl__pureZrandom_u24(s1_671088680, 36n);
  framePtr = F.prev;

  return result_671088678;

}

function skipRandomNumbers__pureZrandom_u45(s_p0) {
  var F = {procname: "random.skipRandomNumbers", prev: framePtr, filename: "C:\\Users\\aine\\.choosenim\\toolchains\\nim-2.2.4\\lib\\pure\\random.nim", line: 0};
  framePtr = F;
    F.line = 218;
    F.filename = "random.nim";
    var s0_671088688 = 0n;
    F.line = 219;
    var s1_671088689 = 0n;
    Label1: {
      F.line = 220;
      var i_671088698 = 0;
      F.line = 96;
      F.filename = "iterators_1.nim";
      var res_536871677 = 0;
      Label2: {
        F.line = 97;
          Label3: while (true) {
          if (!(res_536871677 <= 1)) break Label3;
            F.line = 220;
            F.filename = "random.nim";
            i_671088698 = res_536871677;
            Label4: {
              F.line = 221;
              var b_671088703 = 0;
              F.line = 128;
              F.filename = "iterators_1.nim";
              var i_536871675 = 0;
              Label5: {
                F.line = 129;
                  Label6: while (true) {
                  if (!(i_536871675 < 64)) break Label6;
                    F.line = 221;
                    F.filename = "random.nim";
                    b_671088703 = i_536871675;
                    if (!(((helper_671088687[chckIndx(i_671088698, 0, (helper_671088687).length - 1)] & BigInt.asUintN(64, 1n << BigInt(BigInt.asUintN(64, BigInt(b_671088703))))) == 0n))) {
                    F.line = 223;
                    s0_671088688 = (s0_671088688 ^ s_p0.a0);
                    F.line = 224;
                    s1_671088689 = (s1_671088689 ^ s_p0.a1);
                    }
                    
                    F.line = 225;
                    (next__pureZrandom_u36(s_p0));
                    F.line = 131;
                    F.filename = "iterators_1.nim";
                    i_536871675 = addInt(i_536871675, 1);
                  }
              };
            };
            F.line = 102;
            res_536871677 = addInt(res_536871677, 1);
          }
      };
    };
    F.line = 226;
    F.filename = "random.nim";
    s_p0.a0 = s0_671088688;
    F.line = 227;
    s_p0.a1 = s1_671088689;
  framePtr = F.prev;

  
}

function initRand__pureZrandom_u250(seed_p0) {
    var Temporary1;

  var result_671088892 = [({a0: 0n, a1: 0n})];

  var F = {procname: "random.initRand", prev: framePtr, filename: "C:\\Users\\aine\\.choosenim\\toolchains\\nim-2.2.4\\lib\\pure\\random.nim", line: 0};
  framePtr = F;
    F.line = 606;
    F.filename = "random.nim";
    if (!((seed_p0 == 0n))) {
    Temporary1 = seed_p0;
    }
    else {
    Temporary1 = 2147483647n;
    }
    
    var seed_671088898 = Temporary1;
    F.line = 607;
    result_671088892[0] = nimCopy(result_671088892[0], {a0: BigInt.asUintN(64, (seed_671088898 >> BigInt(16))), a1: BigInt.asUintN(64, (seed_671088898 & 65535n))}, NTI671088644);
    F.line = 611;
    skipRandomNumbers__pureZrandom_u45(result_671088892[0]);
    F.line = 612;
    (next__pureZrandom_u36(result_671088892[0]));
  framePtr = F.prev;

  return result_671088892[0];

}

function initRand__pureZrandom_u292() {
  var result_671088933 = ({a0: 0n, a1: 0n});

  var F = {procname: "random.initRand", prev: framePtr, filename: "C:\\Users\\aine\\.choosenim\\toolchains\\nim-2.2.4\\lib\\pure\\random.nim", line: 0};
  framePtr = F;
    F.line = 698;
    F.filename = "random.nim";
    var time_671088934 = (BigInt(Math.trunc((epochTime__pureZtimes_u4759() * 1000.0))) & 2147483647n);
    F.line = 699;
    result_671088933 = nimCopy(result_671088933, initRand__pureZrandom_u250(time_671088934), NTI671088644);
  framePtr = F.prev;

  return result_671088933;

}

function randomize__pureZrandom_u299() {
  var F = {procname: "random.randomize", prev: framePtr, filename: "C:\\Users\\aine\\.choosenim\\toolchains\\nim-2.2.4\\lib\\pure\\random.nim", line: 0};
  framePtr = F;
    F.line = 753;
    F.filename = "random.nim";
    state_671088655[0] = nimCopy(state_671088655[0], initRand__pureZrandom_u292(), NTI671088644);
  framePtr = F.prev;

  
}

function sysFatal__stdZassertions_u44(message_p1) {
  var F = {procname: "sysFatal.sysFatal", prev: framePtr, filename: "C:\\Users\\aine\\.choosenim\\toolchains\\nim-2.2.4\\lib\\system\\fatal.nim", line: 0};
  framePtr = F;
    F.line = 53;
    F.filename = "fatal.nim";
    raiseException({message: nimCopy(null, message_p1, NTI33554449), m_type: NTI134217745, parent: null, name: null, trace: [], up: null}, "AssertionDefect");
  framePtr = F.prev;

  
}

function raiseAssert__stdZassertions_u42(msg_p0) {
  var F = {procname: "assertions.raiseAssert", prev: framePtr, filename: "C:\\Users\\aine\\.choosenim\\toolchains\\nim-2.2.4\\lib\\std\\assertions.nim", line: 0};
  framePtr = F;
    F.line = 36;
    F.filename = "assertions.nim";
    sysFatal__stdZassertions_u44(msg_p0);
  framePtr = F.prev;

  
}

function failedAssertImpl__stdZassertions_u84(msg_p0) {
  var F = {procname: "assertions.failedAssertImpl", prev: framePtr, filename: "C:\\Users\\aine\\.choosenim\\toolchains\\nim-2.2.4\\lib\\std\\assertions.nim", line: 0};
  framePtr = F;
    F.line = 41;
    F.filename = "assertions.nim";
    raiseAssert__stdZassertions_u42(msg_p0);
  framePtr = F.prev;

  
}

function rand__pureZrandom_u112(r_p0, max_p1) {
  var result_671088756 = 0n;

  var F = {procname: "rand.rand", prev: framePtr, filename: "C:\\Users\\aine\\.choosenim\\toolchains\\nim-2.2.4\\lib\\pure\\random.nim", line: 0};
  framePtr = F;
  BeforeRet: {
    if ((max_p1 == 0n)) {
    F.line = 231;
    F.filename = "random.nim";
    break BeforeRet;
    }
    else {
      F.line = 233;
      var max_671088757 = max_p1;
      if ((max_671088757 == 18446744073709551615n)) {
      F.line = 235;
      result_671088756 = next__pureZrandom_u36(r_p0);
      break BeforeRet;
      }
      
      F.line = 236;
      var iters_671088770 = 0;
      Label1: {
        F.line = 237;
          Label2: while (true) {
          if (!true) break Label2;
            F.line = 238;
            var x_671088771 = next__pureZrandom_u36(r_p0);
            if (((x_671088771 <= BigInt.asUintN(64, (18446744073709551615n - (18446744073709551615n % max_671088757)))) || (20 < iters_671088770))) {
            F.line = 241;
            result_671088756 = (x_671088771 % BigInt.asUintN(64, (max_671088757 + 1n)));
            break BeforeRet;
            }
            else {
              F.line = 243;
            iters_671088770 = addInt(iters_671088770, 1);
            }
            
          }
      };
    }
    
  };
  framePtr = F.prev;

  return result_671088756;

}

function rand__dungeon_u68(r_p0, x_p1) {
  var result_536870984 = 0;

  var F = {procname: "rand.rand", prev: framePtr, filename: "C:\\Users\\aine\\.choosenim\\toolchains\\nim-2.2.4\\lib\\pure\\random.nim", line: 0};
  framePtr = F;
    if (!((x_p1.a <= x_p1.b))) {
    F.line = 347;
    F.filename = "random.nim";
    failedAssertImpl__stdZassertions_u84(makeNimstrLit("C:\\Users\\aine\\.choosenim\\toolchains\\nim-2.2.4\\lib\\pure\\random.nim(347, 3) `x.a <= x.b` "));
    }
    
    F.line = 354;
    result_536870984 = Number(BigInt.asIntN(32, BigInt.asUintN(64, (rand__pureZrandom_u112(r_p0, BigInt.asUintN(64, (BigInt.asUintN(64, BigInt(x_p1.b)) - BigInt.asUintN(64, BigInt(x_p1.a))))) + BigInt.asUintN(64, BigInt(x_p1.a))))));
  framePtr = F.prev;

  return result_536870984;

}

function rand__dungeon_u60(x_p0) {
  var result_536870975 = 0;

  var F = {procname: "rand.rand", prev: framePtr, filename: "C:\\Users\\aine\\.choosenim\\toolchains\\nim-2.2.4\\lib\\pure\\random.nim", line: 0};
  framePtr = F;
    F.line = 376;
    F.filename = "random.nim";
    result_536870975 = rand__dungeon_u68(state_671088655[0], x_p0);
  framePtr = F.prev;

  return result_536870975;

}

function HEX2EHEX2E__stdZstrbasics_u48(a_p0, b_p1) {
  var result_939524149 = ({a: 0, b: 0});

  var F = {procname: ".....", prev: framePtr, filename: "C:\\Users\\aine\\.choosenim\\toolchains\\nim-2.2.4\\lib\\system.nim", line: 0};
  framePtr = F;
    F.line = 436;
    F.filename = "system.nim";
    result_939524149 = nimCopy(result_939524149, {a: a_p0, b: b_p1}, NTI687866351);
  framePtr = F.prev;

  return result_939524149;

}

function getRandomInt(max_p0) {
  var result_536870956 = 0;

  var F = {procname: "dungeon.getRandomInt", prev: framePtr, filename: "D:\\tribenine\\24tribe.github.io\\src\\dungeon.nim", line: 0};
  framePtr = F;
    F.line = 49;
    F.filename = "dungeon.nim";
    result_536870956 = rand__dungeon_u60(HEX2EHEX2E__stdZstrbasics_u48(0, subInt(max_p0, 1)));
  framePtr = F.prev;

  return result_536870956;

}

function createGrid(gridWidth_p0, gridHeight_p1) {
  var result_536870998 = [];

  var F = {procname: "dungeon.createGrid", prev: framePtr, filename: "D:\\tribenine\\24tribe.github.io\\src\\dungeon.nim", line: 0};
  framePtr = F;
    Label1: {
      F.line = 53;
      F.filename = "dungeon.nim";
      var y_536871003 = 0;
      F.line = 128;
      F.filename = "iterators_1.nim";
      var i_536871700 = 0;
      Label2: {
        F.line = 129;
          Label3: while (true) {
          if (!(i_536871700 < gridHeight_p1)) break Label3;
            F.line = 53;
            F.filename = "dungeon.nim";
            y_536871003 = i_536871700;
            F.line = 54;
            var row_536871024 = newSeq__system_u2516(0);
            Label4: {
              F.line = 56;
              var x_536871029 = 0;
              F.line = 128;
              F.filename = "iterators_1.nim";
              var i_536871698 = 0;
              Label5: {
                F.line = 129;
                  Label6: while (true) {
                  if (!(i_536871698 < gridWidth_p0)) break Label6;
                    F.line = 56;
                    F.filename = "dungeon.nim";
                    x_536871029 = i_536871698;
                    F.line = 57;
                    row_536871024.push("N");;
                    F.line = 131;
                    F.filename = "iterators_1.nim";
                    i_536871698 = addInt(i_536871698, 1);
                  }
              };
            };
            F.line = 59;
            F.filename = "dungeon.nim";
            var Temporary7 = nimCopy(null, row_536871024, NTI33556097);
            result_536870998.push(Temporary7);;
            F.line = 131;
            F.filename = "iterators_1.nim";
            i_536871700 = addInt(i_536871700, 1);
          }
      };
    };
  framePtr = F.prev;

  return result_536870998;

}

function contains__pureZtimes_u1783(s_p0, value_p1) {
  var result_838862589 = false;

  var F = {procname: "contains.contains", prev: framePtr, filename: "C:\\Users\\aine\\.choosenim\\toolchains\\nim-2.2.4\\lib\\system.nim", line: 0};
  framePtr = F;
    F.line = 752;
    F.filename = "system.nim";
    result_838862589 = ((s_p0.a <= value_p1) && (value_p1 <= s_p0.b));
  framePtr = F.prev;

  return result_838862589;

}

function validPosition__dungeon_u182(grid_p0, x_p1, y_p2) {
  var result_536871098 = false;

  var F = {procname: "dungeon.validPosition", prev: framePtr, filename: "D:\\tribenine\\24tribe.github.io\\src\\dungeon.nim", line: 0};
  framePtr = F;
    F.line = 72;
    F.filename = "dungeon.nim";
    var gridHeight_536871103 = (grid_p0).length;
    F.line = 73;
    var gridWidth_536871108 = (grid_p0[chckIndx(0, 0, (grid_p0).length - 1)]).length;
    F.line = 74;
    result_536871098 = (contains__pureZtimes_u1783(HEX2EHEX2E__stdZstrbasics_u48(0, subInt(gridWidth_536871108, 1)), x_p1) && contains__pureZtimes_u1783(HEX2EHEX2E__stdZstrbasics_u48(0, subInt(gridHeight_536871103, 1)), y_p2));
  framePtr = F.prev;

  return result_536871098;

}

function setIfValidPos__dungeon_u286(grid_p0, grid_p0_Idx, x_p1, y_p2, val_p3) {
  var F = {procname: "dungeon.setIfValidPos", prev: framePtr, filename: "D:\\tribenine\\24tribe.github.io\\src\\dungeon.nim", line: 0};
  framePtr = F;
    if (validPosition__dungeon_u182(grid_p0[grid_p0_Idx], x_p1, y_p2)) {
    F.line = 90;
    F.filename = "dungeon.nim";
    grid_p0[grid_p0_Idx][chckIndx(y_p2, 0, (grid_p0[grid_p0_Idx]).length - 1)][chckIndx(x_p1, 0, (grid_p0[grid_p0_Idx][chckIndx(y_p2, 0, (grid_p0[grid_p0_Idx]).length - 1)]).length - 1)] = val_p3;
    }
    
  framePtr = F.prev;

  
}

function getNeighbourPositions__dungeon_u126(x_p0, y_p1) {
  var result_536871041 = [];

  var F = {procname: "dungeon.getNeighbourPositions", prev: framePtr, filename: "D:\\tribenine\\24tribe.github.io\\src\\dungeon.nim", line: 0};
  framePtr = F;
    F.line = 63;
    F.filename = "dungeon.nim";
    result_536871041 = nimCopy(null, [new Int32Array([subInt(x_p0, 1), y_p1]), new Int32Array([addInt(x_p0, 1), y_p1]), new Int32Array([x_p0, addInt(y_p1, 1)]), new Int32Array([x_p0, subInt(y_p1, 1)])], NTI536871015);
  framePtr = F.prev;

  return result_536871041;

}

function getPossibleNextPositions__dungeon_u235(x_p0, y_p1, grid_p2) {
  var result_536871151 = [];

  var F = {procname: "dungeon.getPossibleNextPositions", prev: framePtr, filename: "D:\\tribenine\\24tribe.github.io\\src\\dungeon.nim", line: 0};
  framePtr = F;
    Label1: {
      F.line = 78;
      F.filename = "dungeon.nim";
      var pos_536871174 = new Int32Array(2);
      F.line = 247;
      F.filename = "iterators.nim";
      var colontmp__536871705 = [];
      F.line = 78;
      F.filename = "dungeon.nim";
      colontmp__536871705 = getNeighbourPositions__dungeon_u126(x_p0, y_p1);
      F.line = 249;
      F.filename = "iterators.nim";
      var i_536871707 = 0;
      F.line = 250;
      var L_536871708 = (colontmp__536871705).length;
      Label2: {
        F.line = 251;
          Label3: while (true) {
          if (!(i_536871707 < L_536871708)) break Label3;
            F.line = 78;
            F.filename = "dungeon.nim";
            pos_536871174 = colontmp__536871705[chckIndx(i_536871707, 0, (colontmp__536871705).length - 1)];
            F.line = 79;
            var neightbourX_536871175 = pos_536871174[chckIndx(0, 0, (pos_536871174).length - 1)];
            F.line = 80;
            var neightbourY_536871176 = pos_536871174[chckIndx(1, 0, (pos_536871174).length - 1)];
            if (validPosition__dungeon_u182(grid_p2, neightbourX_536871175, neightbourY_536871176)) {
            F.line = 83;
            var node_536871177 = grid_p2[chckIndx(neightbourY_536871176, 0, (grid_p2).length - 1)][chckIndx(neightbourX_536871175, 0, (grid_p2[chckIndx(neightbourY_536871176, 0, (grid_p2).length - 1)]).length - 1)];
            if (((node_536871177 == "N") || (node_536871177 == "O"))) {
            F.line = 85;
            var Temporary4 = nimCopy(null, pos_536871174, NTI536870919);
            result_536871151.push(Temporary4);;
            }
            
            }
            
            F.line = 13;
            F.filename = "iterators.nim";
            i_536871707 += 1;
            if (!(((colontmp__536871705).length == L_536871708))) {
            F.line = 254;
            failedAssertImpl__stdZassertions_u84(makeNimstrLit("C:\\Users\\aine\\.choosenim\\toolchains\\nim-2.2.4\\lib\\system\\iterators.nim(254, 11) `len(a) == L` the length of the seq changed while iterating over it"));
            }
            
          }
      };
    };
  framePtr = F.prev;

  return result_536871151;

}

function pop__dungeon_u310(s_p0, s_p0_Idx) {
  var result_536871225 = new Int32Array(2);

  var F = {procname: "pop.pop", prev: framePtr, filename: "C:\\Users\\aine\\.choosenim\\toolchains\\nim-2.2.4\\lib\\system.nim", line: 0};
  framePtr = F;
    F.line = 1790;
    F.filename = "system.nim";
    var L_536871229 = subInt((s_p0[s_p0_Idx]).length, 1);
    F.line = 1795;
    result_536871225 = nimCopy(result_536871225, s_p0[s_p0_Idx][chckIndx(L_536871229, 0, (s_p0[s_p0_Idx]).length - 1)], NTI536870919);
    F.line = 1796;
    if (s_p0[s_p0_Idx].length < chckRange(L_536871229, 0, 2147483647)) { for (var i = s_p0[s_p0_Idx].length ; i < chckRange(L_536871229, 0, 2147483647) ; ++i) s_p0[s_p0_Idx].push(new Int32Array(2)); }
               else { s_p0[s_p0_Idx].length = chckRange(L_536871229, 0, 2147483647); };
  framePtr = F.prev;

  return result_536871225;

}

function getPath(gridWidth_p0, gridHeight_p1) {
  var result_536871206 = [[]];

  var F = {procname: "dungeon.getPath", prev: framePtr, filename: "D:\\tribenine\\24tribe.github.io\\src\\dungeon.nim", line: 0};
  framePtr = F;
    F.line = 94;
    F.filename = "dungeon.nim";
    var grid_536871207 = [createGrid(gridWidth_p0, gridHeight_p1)];
    F.line = 96;
    var objX_536871208 = getRandomInt(gridWidth_p0);
    F.line = 97;
    var objY_536871209 = 0;
    F.line = 98;
    var startX_536871210 = getRandomInt(gridWidth_p0);
    F.line = 99;
    var startY_536871211 = subInt(gridHeight_p1, 1);
    F.line = 101;
    setIfValidPos__dungeon_u286(grid_536871207, 0, subInt(objX_536871208, 1), objY_536871209, "V");
    F.line = 102;
    setIfValidPos__dungeon_u286(grid_536871207, 0, addInt(objX_536871208, 1), objY_536871209, "V");
    F.line = 103;
    grid_536871207[0][chckIndx(objY_536871209, 0, (grid_536871207[0]).length - 1)][chckIndx(objX_536871208, 0, (grid_536871207[0][chckIndx(objY_536871209, 0, (grid_536871207[0]).length - 1)]).length - 1)] = "O";
    F.line = 105;
    grid_536871207[0][chckIndx(startY_536871211, 0, (grid_536871207[0]).length - 1)][chckIndx(startX_536871210, 0, (grid_536871207[0][chckIndx(startY_536871211, 0, (grid_536871207[0]).length - 1)]).length - 1)] = "V";
    F.line = 106;
    setIfValidPos__dungeon_u286(grid_536871207, 0, subInt(startX_536871210, 1), startY_536871211, "V");
    F.line = 107;
    setIfValidPos__dungeon_u286(grid_536871207, 0, addInt(startX_536871210, 1), startY_536871211, "V");
    F.line = 109;
    result_536871206[0].push(new Int32Array([startX_536871210, startY_536871211]));;
    F.line = 111;
    var x_536871216 = startX_536871210;
    F.line = 112;
    var y_536871217 = startY_536871211;
    Label1: {
      F.line = 114;
        Label2: while (true) {
        if (!!((grid_536871207[0][chckIndx(y_536871217, 0, (grid_536871207[0]).length - 1)][chckIndx(x_536871216, 0, (grid_536871207[0][chckIndx(y_536871217, 0, (grid_536871207[0]).length - 1)]).length - 1)] == "O"))) break Label2;
          Label3: {
            F.line = 115;
            var nextPositions_536871218 = getPossibleNextPositions__dungeon_u235(x_536871216, y_536871217, grid_536871207[0]);
            if (((nextPositions_536871218).length == 0)) {
            F.line = 118;
            (pop__dungeon_u310(result_536871206, 0));
            F.line = 119;
            var lastPos_536871237 = nimCopy(null, result_536871206[0][chckIndx(subInt((result_536871206[0]).length, 1), 0, (result_536871206[0]).length - 1)], NTI536870919);
            F.line = 120;
            x_536871216 = lastPos_536871237[chckIndx(0, 0, (lastPos_536871237).length - 1)];
            F.line = 121;
            y_536871217 = lastPos_536871237[chckIndx(1, 0, (lastPos_536871237).length - 1)];
            F.line = 122;
            break Label3;
            }
            
            F.line = 124;
            var nextPos_536871241 = nimCopy(null, nextPositions_536871218[chckIndx(getRandomInt((nextPositions_536871218).length), 0, (nextPositions_536871218).length - 1)], NTI536870919);
            F.line = 125;
            var nextPosX_536871242 = nextPos_536871241[chckIndx(0, 0, (nextPos_536871241).length - 1)];
            F.line = 126;
            var nextPosY_536871243 = nextPos_536871241[chckIndx(1, 0, (nextPos_536871241).length - 1)];
            if (!((grid_536871207[0][chckIndx(nextPosY_536871243, 0, (grid_536871207[0]).length - 1)][chckIndx(nextPosX_536871242, 0, (grid_536871207[0][chckIndx(nextPosY_536871243, 0, (grid_536871207[0]).length - 1)]).length - 1)] == "O"))) {
            F.line = 129;
            grid_536871207[0][chckIndx(nextPosY_536871243, 0, (grid_536871207[0]).length - 1)][chckIndx(nextPosX_536871242, 0, (grid_536871207[0][chckIndx(nextPosY_536871243, 0, (grid_536871207[0]).length - 1)]).length - 1)] = "V";
            }
            
            F.line = 131;
            x_536871216 = nextPosX_536871242;
            F.line = 132;
            y_536871217 = nextPosY_536871243;
            F.line = 134;
            result_536871206[0].push(new Int32Array([x_536871216, y_536871217]));;
          };
        }
    };
  framePtr = F.prev;

  return result_536871206[0];

}

function splitDungeonParts(dungeonData_p0) {
  var result_536871266 = ({startPart: null, endPart: null, middleParts: []});

  var F = {procname: "dungeon.splitDungeonParts", prev: framePtr, filename: "D:\\tribenine\\24tribe.github.io\\src\\dungeon.nim", line: 0};
  framePtr = F;
    Label1: {
      F.line = 138;
      F.filename = "dungeon.nim";
      var dungeonpart_536871289 = null;
      F.line = 249;
      F.filename = "iterators.nim";
      var i_536871712 = 0;
      F.line = 250;
      var L_536871713 = (dungeonData_p0).length;
      Label2: {
        F.line = 251;
          Label3: while (true) {
          if (!(i_536871712 < L_536871713)) break Label3;
            F.line = 138;
            F.filename = "dungeon.nim";
            dungeonpart_536871289 = dungeonData_p0[chckIndx(i_536871712, 0, (dungeonData_p0).length - 1)];
            if ((dungeonpart_536871289.id == 101)) {
            F.line = 140;
            result_536871266.startPart = dungeonpart_536871289;
            }
            else {
            if ((dungeonpart_536871289.id == 201)) {
            F.line = 142;
            result_536871266.endPart = dungeonpart_536871289;
            }
            else {
              F.line = 144;
            result_536871266.middleParts.push(dungeonpart_536871289);;
            }
            }
            F.line = 13;
            F.filename = "iterators.nim";
            i_536871712 += 1;
            if (!(((dungeonData_p0).length == L_536871713))) {
            F.line = 254;
            failedAssertImpl__stdZassertions_u84(makeNimstrLit("C:\\Users\\aine\\.choosenim\\toolchains\\nim-2.2.4\\lib\\system\\iterators.nim(254, 11) `len(a) == L` the length of the seq changed while iterating over it"));
            }
            
          }
      };
    };
  framePtr = F.prev;

  return result_536871266;

}

function updateEntrances(entrances_p0, nodePos_p1, otherNodePos_p2) {
  var F = {procname: "dungeon.updateEntrances", prev: framePtr, filename: "D:\\tribenine\\24tribe.github.io\\src\\dungeon.nim", line: 0};
  framePtr = F;
    F.line = 148;
    F.filename = "dungeon.nim";
    var diffX_536871362 = subInt(nodePos_p1[chckIndx(0, 0, (nodePos_p1).length - 1)], otherNodePos_p2[chckIndx(0, 0, (otherNodePos_p2).length - 1)]);
    F.line = 149;
    var diffY_536871363 = subInt(nodePos_p1[chckIndx(1, 0, (nodePos_p1).length - 1)], otherNodePos_p2[chckIndx(1, 0, (otherNodePos_p2).length - 1)]);
    if ((diffX_536871362 == 1)) {
    F.line = 152;
    entrances_p0.right = 1;
    }
    else {
    if ((diffX_536871362 == (-1))) {
    F.line = 154;
    entrances_p0.left = 1;
    }
    }
    if ((diffY_536871363 == 1)) {
    F.line = 157;
    entrances_p0.bottom = 1;
    }
    else {
    if ((diffY_536871363 == (-1))) {
    F.line = 159;
    entrances_p0.top = 1;
    }
    }
  framePtr = F.prev;

  
}

function getMiddleNodesEntrances(path_p0) {
  var result_536871366 = [];

  var F = {procname: "dungeon.getMiddleNodesEntrances", prev: framePtr, filename: "D:\\tribenine\\24tribe.github.io\\src\\dungeon.nim", line: 0};
  framePtr = F;
    Label1: {
      F.line = 163;
      F.filename = "dungeon.nim";
      var i_536871374 = 0;
      F.line = 126;
      F.filename = "iterators_1.nim";
      var colontmp__536871716 = 0;
      F.line = 163;
      F.filename = "dungeon.nim";
      colontmp__536871716 = subInt((path_p0).length, 1);
      F.line = 128;
      F.filename = "iterators_1.nim";
      var i_536871717 = 1;
      Label2: {
        F.line = 129;
          Label3: while (true) {
          if (!(i_536871717 < colontmp__536871716)) break Label3;
            F.line = 163;
            F.filename = "dungeon.nim";
            i_536871374 = i_536871717;
            F.line = 164;
            var entrances_536871375 = [{top: 0, right: 0, bottom: 0, left: 0}];
            F.line = 165;
            var nodePos_536871376 = nimCopy(null, path_p0[chckIndx(i_536871374, 0, (path_p0).length - 1)], NTI536870919);
            F.line = 166;
            var lastNodePos_536871377 = nimCopy(null, path_p0[chckIndx(subInt(i_536871374, 1), 0, (path_p0).length - 1)], NTI536870919);
            F.line = 167;
            var nextNodePos_536871378 = nimCopy(null, path_p0[chckIndx(addInt(i_536871374, 1), 0, (path_p0).length - 1)], NTI536870919);
            F.line = 169;
            updateEntrances(entrances_536871375[0], lastNodePos_536871377, nodePos_536871376);
            F.line = 170;
            updateEntrances(entrances_536871375[0], nextNodePos_536871378, nodePos_536871376);
            F.line = 172;
            var Temporary4 = nimCopy(null, entrances_536871375[0], NTI536870934);
            result_536871366.push(Temporary4);;
            F.line = 131;
            F.filename = "iterators_1.nim";
            i_536871717 = addInt(i_536871717, 1);
          }
      };
    };
  framePtr = F.prev;

  return result_536871366;

}

function dungeonPartToDungeonPiece(dungeonPart_p0, cityId_p1) {
  var result_536871405 = ({x: 0, y: 0, rotate: 0, dungeonPieceId: 0});

  var F = {procname: "dungeon.dungeonPartToDungeonPiece", prev: framePtr, filename: "D:\\tribenine\\24tribe.github.io\\src\\dungeon.nim", line: 0};
  framePtr = F;
    F.line = 176;
    F.filename = "dungeon.nim";
    result_536871405 = nimCopy(result_536871405, {x: dungeonPart_p0.blocks[chckIndx(0, 0, (dungeonPart_p0.blocks).length - 1)].x, y: dungeonPart_p0.blocks[chckIndx(0, 0, (dungeonPart_p0.blocks).length - 1)].y, rotate: dungeonPart_p0.angle, dungeonPieceId: addInt(mulInt(cityId_p1, 10000), dungeonPart_p0.id)}, NTI536870932);
  framePtr = F.prev;

  return result_536871405;

}

function copyAndApplyPos(part_p0, pos_p1) {
  var result_536871428 = null;

  var F = {procname: "dungeon.copyAndApplyPos", prev: framePtr, filename: "D:\\tribenine\\24tribe.github.io\\src\\dungeon.nim", line: 0};
  framePtr = F;
    F.line = 185;
    F.filename = "dungeon.nim";
    result_536871428 = ({id: 0, name: null, blocks: [], angle: 0});
    F.line = 186;
    result_536871428.id = part_p0.id;
    F.line = 187;
    result_536871428.name = part_p0.name;
    F.line = 188;
    result_536871428.angle = part_p0.angle;
    Label1: {
      F.line = 190;
      var oldBlock_536871454 = ({x: 0, y: 0, top: 0, right: 0, bottom: 0, left: 0});
      F.line = 249;
      F.filename = "iterators.nim";
      var i_536871721 = 0;
      F.line = 250;
      var L_536871722 = (part_p0.blocks).length;
      Label2: {
        F.line = 251;
          Label3: while (true) {
          if (!(i_536871721 < L_536871722)) break Label3;
            F.line = 190;
            F.filename = "dungeon.nim";
            oldBlock_536871454 = part_p0.blocks[chckIndx(i_536871721, 0, (part_p0.blocks).length - 1)];
            F.line = 191;
            var newBlock_536871455 = {x: addInt(oldBlock_536871454.x, pos_p1[chckIndx(0, 0, (pos_p1).length - 1)]), y: addInt(oldBlock_536871454.y, pos_p1[chckIndx(1, 0, (pos_p1).length - 1)]), top: 0, right: 0, bottom: 0, left: 0};
            F.line = 192;
            var Temporary4 = nimCopy(null, newBlock_536871455, NTI536870933);
            result_536871428.blocks.push(Temporary4);;
            F.line = 13;
            F.filename = "iterators.nim";
            i_536871721 += 1;
            if (!(((part_p0.blocks).length == L_536871722))) {
            F.line = 254;
            failedAssertImpl__stdZassertions_u84(makeNimstrLit("C:\\Users\\aine\\.choosenim\\toolchains\\nim-2.2.4\\lib\\system\\iterators.nim(254, 11) `len(a) == L` the length of the seq changed while iterating over it"));
            }
            
          }
      };
    };
  framePtr = F.prev;

  return result_536871428;

}

function none__dungeon_u642() {
  var result_536871561 = ({val: ({x: 0, y: 0, top: 0, right: 0, bottom: 0, left: 0}), has: false});

  var F = {procname: "none.none", prev: framePtr, filename: "C:\\Users\\aine\\.choosenim\\toolchains\\nim-2.2.4\\lib\\pure\\options.nim", line: 0};
  framePtr = F;
    F.line = 155;
    F.filename = "options.nim";
    result_536871561 = nimCopy(result_536871561, {val: ({x: 0, y: 0, top: 0, right: 0, bottom: 0, left: 0}), has: false}, NTI536871325);
  framePtr = F.prev;

  return result_536871561;

}

function equalEntrances__dungeon_u620(entrances1_p0, entrances2_p1) {
  var result_536871535 = false;

  var F = {procname: "dungeon.equalEntrances", prev: framePtr, filename: "D:\\tribenine\\24tribe.github.io\\src\\dungeon.nim", line: 0};
  framePtr = F;
    F.line = 198;
    F.filename = "dungeon.nim";
    result_536871535 = ((((entrances1_p0.top == entrances2_p1.top) && (entrances1_p0.right == entrances2_p1.right)) && (entrances1_p0.bottom == entrances2_p1.bottom)) && (entrances1_p0.left == entrances2_p1.left));
  framePtr = F.prev;

  return result_536871535;

}

function isSome__dungeon_u685(self_p0) {
  var result_536871600 = false;

  var F = {procname: "isSome.isSome", prev: framePtr, filename: "C:\\Users\\aine\\.choosenim\\toolchains\\nim-2.2.4\\lib\\pure\\options.nim", line: 0};
  framePtr = F;
    F.line = 162;
    F.filename = "options.nim";
    result_536871600 = self_p0.has;
  framePtr = F.prev;

  return result_536871600;

}

function isNone__dungeon_u714(self_p0) {
  var result_536871629 = false;

  var F = {procname: "isNone.isNone", prev: framePtr, filename: "C:\\Users\\aine\\.choosenim\\toolchains\\nim-2.2.4\\lib\\pure\\options.nim", line: 0};
  framePtr = F;
    F.line = 177;
    F.filename = "options.nim";
    result_536871629 = !(self_p0.has);
  framePtr = F.prev;

  return result_536871629;

}

function get__dungeon_u706(self_p0) {
  var result_536871621 = null;

  var F = {procname: "get.get", prev: framePtr, filename: "C:\\Users\\aine\\.choosenim\\toolchains\\nim-2.2.4\\lib\\pure\\options.nim", line: 0};
  framePtr = F;
  BeforeRet: {
    if (isNone__dungeon_u714(self_p0)) {
    F.line = 231;
    F.filename = "options.nim";
    raiseException({message: [67,97,110,39,116,32,111,98,116,97,105,110,32,97,32,118,97,108,117,101,32,102,114,111,109,32,97,32,96,110,111,110,101,96], parent: null, m_type: NTI989855767, name: null, trace: [], up: null}, "UnpackDefect");
    }
    
    F.line = 232;
    result_536871621 = self_p0.val;
    break BeforeRet;
  };
  framePtr = F.prev;

  return result_536871621;

}

function some__dungeon_u751(val_p0) {
  var result_536871666 = ({val: ({x: 0, y: 0, top: 0, right: 0, bottom: 0, left: 0}), has: false});

  var F = {procname: "some.some", prev: framePtr, filename: "C:\\Users\\aine\\.choosenim\\toolchains\\nim-2.2.4\\lib\\pure\\options.nim", line: 0};
  framePtr = F;
    F.line = 142;
    F.filename = "options.nim";
    result_536871666 = nimCopy(result_536871666, {has: true, val: nimCopy(null, val_p0, NTI536870933)}, NTI536871312);
  framePtr = F.prev;

  return result_536871666;

}

function partCanFit(i_p0, part_p1, path_p2, middleNodesEntrances_p3) {
  var result_536871541 = false;

  var F = {procname: "dungeon.partCanFit", prev: framePtr, filename: "D:\\tribenine\\24tribe.github.io\\src\\dungeon.nim", line: 0};
  framePtr = F;
  BeforeRet: {
    if (((path_p2).length <= addInt(i_p0, (part_p1.blocks).length))) {
    F.line = 206;
    F.filename = "dungeon.nim";
    result_536871541 = false;
    break BeforeRet;
    }
    
    F.line = 208;
    var j_536871548 = 0;
    F.line = 209;
    var lastBlock_536871586 = [none__dungeon_u642()];
    Label1: {
      F.line = 211;
      var bloc_536871590 = ({x: 0, y: 0, top: 0, right: 0, bottom: 0, left: 0});
      F.line = 249;
      F.filename = "iterators.nim";
      var i_536871725 = 0;
      F.line = 250;
      var L_536871726 = (part_p1.blocks).length;
      Label2: {
        F.line = 251;
          Label3: while (true) {
          if (!(i_536871725 < L_536871726)) break Label3;
            F.line = 211;
            F.filename = "dungeon.nim";
            bloc_536871590 = part_p1.blocks[chckIndx(i_536871725, 0, (part_p1.blocks).length - 1)];
            F.line = 212;
            var entrances_536871591 = nimCopy(null, middleNodesEntrances_p3[chckIndx(addInt(subInt(i_p0, 1), j_536871548), 0, (middleNodesEntrances_p3).length - 1)], NTI536870934);
            F.line = 213;
            var blockEntrances_536871592 = {top: bloc_536871590.top, right: bloc_536871590.right, bottom: bloc_536871590.bottom, left: bloc_536871590.left};
            if (!(equalEntrances__dungeon_u620(entrances_536871591, blockEntrances_536871592))) {
            F.line = 219;
            result_536871541 = false;
            break BeforeRet;
            }
            
            if (isSome__dungeon_u685(lastBlock_536871586[0])) {
            F.line = 222;
            var lastNodePos_536871602 = nimCopy(null, path_p2[chckIndx(subInt(addInt(i_p0, j_536871548), 1), 0, (path_p2).length - 1)], NTI536870919);
            F.line = 223;
            var nodePos_536871603 = nimCopy(null, path_p2[chckIndx(addInt(i_p0, j_536871548), 0, (path_p2).length - 1)], NTI536870919);
            F.line = 224;
            var diffX_536871604 = subInt(nodePos_536871603[chckIndx(0, 0, (nodePos_536871603).length - 1)], lastNodePos_536871602[chckIndx(0, 0, (lastNodePos_536871602).length - 1)]);
            F.line = 225;
            var diffY_536871605 = subInt(nodePos_536871603[chckIndx(1, 0, (nodePos_536871603).length - 1)], lastNodePos_536871602[chckIndx(1, 0, (lastNodePos_536871602).length - 1)]);
            if ((!((subInt(bloc_536871590.x, get__dungeon_u706(lastBlock_536871586[0]).x) == diffX_536871604)) || !((subInt(bloc_536871590.y, get__dungeon_u706(lastBlock_536871586[0]).y) == diffY_536871605)))) {
            F.line = 228;
            result_536871541 = false;
            break BeforeRet;
            }
            
            }
            
            F.line = 230;
            lastBlock_536871586[0] = nimCopy(lastBlock_536871586[0], some__dungeon_u751(bloc_536871590), NTI536871312);
            F.line = 231;
            j_536871548 = addInt(j_536871548, 1);
            F.line = 13;
            F.filename = "iterators.nim";
            i_536871725 += 1;
            if (!(((part_p1.blocks).length == L_536871726))) {
            F.line = 254;
            failedAssertImpl__stdZassertions_u84(makeNimstrLit("C:\\Users\\aine\\.choosenim\\toolchains\\nim-2.2.4\\lib\\system\\iterators.nim(254, 11) `len(a) == L` the length of the seq changed while iterating over it"));
            }
            
          }
      };
    };
    F.line = 233;
    F.filename = "dungeon.nim";
    result_536871541 = true;
    break BeforeRet;
  };
  framePtr = F.prev;

  return result_536871541;

}
var F = {procname: "module dungeon", prev: framePtr, filename: "D:\\tribenine\\24tribe.github.io\\src\\dungeon.nim", line: 0};
framePtr = F;
F.line = 4;
F.filename = "dungeon.nim";
randomize__pureZrandom_u299();
framePtr = F.prev;
var F = {procname: "module dungeon", prev: framePtr, filename: "D:\\tribenine\\24tribe.github.io\\src\\dungeon.nim", line: 0};
framePtr = F;
framePtr = F.prev;
