/* Generated by the Nim Compiler v2.2.4 */
var framePtr = null;
var excHandler = 0;
var lastJSError = null;
var NTI536870932 = {size: 0, kind: 18, base: null, node: null, finalizer: null};
var NTI536870934 = {size: 0, kind: 18, base: null, node: null, finalizer: null};
var NTI536870919 = {size: 0, kind: 16, base: null, node: null, finalizer: null};
var NTI536871001 = {size: 0, kind: 16, base: null, node: null, finalizer: null};
var NTI536871015 = {size: 0, kind: 24, base: null, node: null, finalizer: null};
var NTI33556097 = {size: 0, kind: 24, base: null, node: null, finalizer: null};
var NTI687866351 = {size: 0, kind: 18, base: null, node: null, finalizer: null};
var NTI134217745 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI134217749 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI134217751 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33554435 = {size: 0,kind: 31,base: null,node: null,finalizer: null};
var NTI33555836 = {size: 0, kind: 18, base: null, node: null, finalizer: null};
var NTI33555167 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33555175 = {size: 0, kind: 22, base: null, node: null, finalizer: null};
var NTI33554450 = {size: 0,kind: 29,base: null,node: null,finalizer: null};
var NTI33555174 = {size: 0, kind: 22, base: null, node: null, finalizer: null};
var NTI33555171 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33555172 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI134217741 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI134217743 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33554449 = {size: 0,kind: 28,base: null,node: null,finalizer: null};
var NTI671088643 = {size: 0,kind: 44,base: null,node: null,finalizer: null};
var NTI671088644 = {size: 0, kind: 18, base: null, node: null, finalizer: null};
var NNI671088644 = {kind: 2, len: 2, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "a0", len: 0, typ: NTI671088643, name: "a0", sons: null}, 
{kind: 1, offset: "a1", len: 0, typ: NTI671088643, name: "a1", sons: null}]};
NTI671088644.node = NNI671088644;
var NNI134217743 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217743.node = NNI134217743;
var NNI134217741 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217741.node = NNI134217741;
var NNI33555172 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI33555172.node = NNI33555172;
NTI33555174.base = NTI33555171;
NTI33555175.base = NTI33555171;
var NNI33555171 = {kind: 2, len: 5, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "parent", len: 0, typ: NTI33555174, name: "parent", sons: null}, 
{kind: 1, offset: "name", len: 0, typ: NTI33554450, name: "name", sons: null}, 
{kind: 1, offset: "message", len: 0, typ: NTI33554449, name: "msg", sons: null}, 
{kind: 1, offset: "trace", len: 0, typ: NTI33554449, name: "trace", sons: null}, 
{kind: 1, offset: "up", len: 0, typ: NTI33555175, name: "up", sons: null}]};
NTI33555171.node = NNI33555171;
var NNI33555167 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI33555167.node = NNI33555167;
NTI33555171.base = NTI33555167;
NTI33555172.base = NTI33555171;
NTI134217741.base = NTI33555172;
NTI134217743.base = NTI134217741;
var NNI33555836 = {kind: 2, len: 3, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "Field0", len: 0, typ: NTI33554450, name: "Field0", sons: null}, 
{kind: 1, offset: "Field1", len: 0, typ: NTI33554435, name: "Field1", sons: null}, 
{kind: 1, offset: "Field2", len: 0, typ: NTI33554450, name: "Field2", sons: null}]};
NTI33555836.node = NNI33555836;
var NNI134217751 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217751.node = NNI134217751;
NTI134217751.base = NTI33555172;
var NNI134217749 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217749.node = NNI134217749;
NTI134217749.base = NTI33555172;
var NNI134217745 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217745.node = NNI134217745;
NTI134217745.base = NTI33555172;
var NNI687866351 = {kind: 2, len: 2, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "a", len: 0, typ: NTI33554435, name: "a", sons: null}, 
{kind: 1, offset: "b", len: 0, typ: NTI33554435, name: "b", sons: null}]};
NTI687866351.node = NNI687866351;
NTI33556097.base = NTI33554450;
NTI536871001.base = NTI33554435;
NTI536871015.base = NTI536871001;
NTI536870919.base = NTI33554435;
var NNI536870934 = {kind: 2, len: 4, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "top", len: 0, typ: NTI33554435, name: "top", sons: null}, 
{kind: 1, offset: "right", len: 0, typ: NTI33554435, name: "right", sons: null}, 
{kind: 1, offset: "bottom", len: 0, typ: NTI33554435, name: "bottom", sons: null}, 
{kind: 1, offset: "left", len: 0, typ: NTI33554435, name: "left", sons: null}]};
NTI536870934.node = NNI536870934;
var NNI536870932 = {kind: 2, len: 4, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "x", len: 0, typ: NTI33554435, name: "x", sons: null}, 
{kind: 1, offset: "y", len: 0, typ: NTI33554435, name: "y", sons: null}, 
{kind: 1, offset: "rotate", len: 0, typ: NTI33554435, name: "rotate", sons: null}, 
{kind: 1, offset: "dungeonPieceId", len: 0, typ: NTI33554435, name: "dungeonPieceId", sons: null}]};
NTI536870932.node = NNI536870932;
var DefaultRandSeed_671088654 = {a0: 7616934476015405061n, a1: 15122295919272093642n};

function setConstr() {
        var result = {};
    for (var i = 0; i < arguments.length; ++i) {
      var x = arguments[i];
      if (typeof(x) == "object") {
        for (var j = x[0]; j <= x[1]; ++j) {
          result[j] = true;
        }
      } else {
        result[x] = true;
      }
    }
    return result;
  

  
}
var ConstSet1 = setConstr(17, 16, 4, 18, 27, 19, 23, 22, 21);

function nimCopy(dest_p0, src_p1, ti_p2) {
  var result_33557330 = null;

    switch (ti_p2.kind) {
    case 21:
    case 22:
    case 23:
    case 5:
      if (!(isFatPointer__system_u2878(ti_p2))) {
      result_33557330 = src_p1;
      }
      else {
        result_33557330 = [src_p1[0], src_p1[1]];
      }
      
      break;
    case 19:
            if (dest_p0 === null || dest_p0 === undefined) {
        dest_p0 = {};
      }
      else {
        for (var key in dest_p0) { delete dest_p0[key]; }
      }
      for (var key in src_p1) { dest_p0[key] = src_p1[key]; }
      result_33557330 = dest_p0;
    
      break;
    case 18:
    case 17:
      if (!((ti_p2.base == null))) {
      result_33557330 = nimCopy(dest_p0, src_p1, ti_p2.base);
      }
      else {
      if ((ti_p2.kind == 17)) {
      result_33557330 = (dest_p0 === null || dest_p0 === undefined) ? {m_type: ti_p2} : dest_p0;
      }
      else {
        result_33557330 = (dest_p0 === null || dest_p0 === undefined) ? {} : dest_p0;
      }
      }
      nimCopyAux(result_33557330, src_p1, ti_p2.node);
      break;
    case 4:
    case 16:
            if(ArrayBuffer.isView(src_p1)) { 
        if(dest_p0 === null || dest_p0 === undefined || dest_p0.length != src_p1.length) {
          dest_p0 = new src_p1.constructor(src_p1);
        } else {
          dest_p0.set(src_p1, 0);
        }
        result_33557330 = dest_p0;
      } else {
        if (src_p1 === null) {
          result_33557330 = null;
        }
        else {
          if (dest_p0 === null || dest_p0 === undefined || dest_p0.length != src_p1.length) {
            dest_p0 = new Array(src_p1.length);
          }
          result_33557330 = dest_p0;
          for (var i = 0; i < src_p1.length; ++i) {
            result_33557330[i] = nimCopy(result_33557330[i], src_p1[i], ti_p2.base);
          }
        }
      }
    
      break;
    case 24:
    case 27:
            if (src_p1 === null) {
        result_33557330 = null;
      }
      else {
        if (dest_p0 === null || dest_p0 === undefined || dest_p0.length != src_p1.length) {
          dest_p0 = new Array(src_p1.length);
        }
        result_33557330 = dest_p0;
        for (var i = 0; i < src_p1.length; ++i) {
          result_33557330[i] = nimCopy(result_33557330[i], src_p1[i], ti_p2.base);
        }
      }
    
      break;
    case 28:
            if (src_p1 !== null) {
        result_33557330 = src_p1.slice(0);
      }
    
      break;
    default: 
      result_33557330 = src_p1;
      break;
    }

  return result_33557330;

}
                      var helper_671088687 = new BigUint64Array([13739361407582206667n, 15594563132006766882n]);

function mnewString(len_p0) {
        var result = new Array(len_p0);
    for (var i = 0; i < len_p0; i++) {result[i] = 0;}
    return result;
  

  
}

function arrayConstr(len_p0, value_p1, typ_p2) {
        var result = new Array(len_p0);
    for (var i = 0; i < len_p0; ++i) result[i] = nimCopy(null, value_p1, typ_p2);
    return result;
  

  
}

function cstrToNimstr(c_p0) {
      var ln = c_p0.length;
  var result = new Array(ln);
  var r = 0;
  for (var i = 0; i < ln; ++i) {
    var ch = c_p0.charCodeAt(i);

    if (ch < 128) {
      result[r] = ch;
    }
    else {
      if (ch < 2048) {
        result[r] = (ch >> 6) | 192;
      }
      else {
        if (ch < 55296 || ch >= 57344) {
          result[r] = (ch >> 12) | 224;
        }
        else {
            ++i;
            ch = 65536 + (((ch & 1023) << 10) | (c_p0.charCodeAt(i) & 1023));
            result[r] = (ch >> 18) | 240;
            ++r;
            result[r] = ((ch >> 12) & 63) | 128;
        }
        ++r;
        result[r] = ((ch >> 6) & 63) | 128;
      }
      ++r;
      result[r] = (ch & 63) | 128;
    }
    ++r;
  }
  return result;
  

  
}

function isObj(obj_p0, subclass_p1) {
  var result_33557443 = false;

  BeforeRet: {
    var x_33557444 = obj_p0;
    if ((x_33557444 == subclass_p1)) {
    result_33557443 = true;
    break BeforeRet;
    }
    
    Label1: {
        Label2: while (true) {
        if (!!((x_33557444 == subclass_p1))) break Label2;
          if ((x_33557444 == null)) {
          result_33557443 = false;
          break BeforeRet;
          }
          
          x_33557444 = x_33557444.base;
        }
    };
    result_33557443 = true;
    break BeforeRet;
  };

  return result_33557443;

}

function toJSStr(s_p0) {
  var result_33556919 = null;

    var res_33556973 = newSeq__system_u2516((s_p0).length);
    var i_33556974 = 0;
    var j_33556975 = 0;
    Label1: {
        Label2: while (true) {
        if (!(i_33556974 < (s_p0).length)) break Label2;
          var c_33556976 = s_p0[i_33556974];
          if ((c_33556976 < 128)) {
          res_33556973[j_33556975] = String.fromCharCode(c_33556976);
          i_33556974 += 1;
          }
          else {
            var helper_33557002 = newSeq__system_u2516(0);
            Label3: {
                Label4: while (true) {
                if (!true) break Label4;
                  var code_33557003 = c_33556976.toString(16);
                  if ((((code_33557003) == null ? 0 : (code_33557003).length) == 1)) {
                  helper_33557002.push("%0");;
                  }
                  else {
                  helper_33557002.push("%");;
                  }
                  
                  helper_33557002.push(code_33557003);;
                  i_33556974 += 1;
                  if ((((s_p0).length <= i_33556974) || (s_p0[i_33556974] < 128))) {
                  break Label3;
                  }
                  
                  c_33556976 = s_p0[i_33556974];
                }
            };
++excHandler;
            try {
            res_33556973[j_33556975] = decodeURIComponent(helper_33557002.join(""));
--excHandler;
} catch (EXCEPTION) {
 var prevJSError = lastJSError;
 lastJSError = EXCEPTION;
 --excHandler;
            raiseDefect();
            res_33556973[j_33556975] = helper_33557002.join("");
            lastJSError = prevJSError;
            } finally {
            }
          }
          
          j_33556975 += 1;
        }
    };
    if (res_33556973.length < j_33556975) { for (var i = res_33556973.length ; i < j_33556975 ; ++i) res_33556973.push(null); }
               else { res_33556973.length = j_33556975; };
    result_33556919 = res_33556973.join("");

  return result_33556919;

}

function raiseException(e_p0, ename_p1) {
    e_p0.name = ename_p1;
    if ((excHandler == 0)) {
    unhandledException(e_p0);
    }
    
    e_p0.trace = nimCopy(null, rawWriteStackTrace__system_u2180(), NTI33554449);
    throw e_p0;

  
}

function addInt(a_p0, b_p1) {
        var result = a_p0 + b_p1;
    checkOverflowInt(result);
    return result;
  

  
}

function chckRange(i_p0, a_p1, b_p2) {
  var result_33557370 = 0;

  BeforeRet: {
    if (((a_p1 <= i_p0) && (i_p0 <= b_p2))) {
    result_33557370 = i_p0;
    break BeforeRet;
    }
    else {
    raiseRangeError();
    }
    
  };

  return result_33557370;

}

function chckIndx(i_p0, a_p1, b_p2) {
  var result_33557365 = 0;

  BeforeRet: {
    if (((a_p1 <= i_p0) && (i_p0 <= b_p2))) {
    result_33557365 = i_p0;
    break BeforeRet;
    }
    else {
    raiseIndexError(i_p0, a_p1, b_p2);
    }
    
  };

  return result_33557365;

}

function makeNimstrLit(c_p0) {
      var result = [];
  for (var i = 0; i < c_p0.length; ++i) {
    result[i] = c_p0.charCodeAt(i);
  }
  return result;
  

  
}

function subInt(a_p0, b_p1) {
        var result = a_p0 - b_p1;
    checkOverflowInt(result);
    return result;
  

  
}

function mulInt(a_p0, b_p1) {
        var result = a_p0 * b_p1;
    checkOverflowInt(result);
    return result;
  

  
}
var F = {procname: "module algorithm", prev: framePtr, filename: "C:\\Users\\aine\\.choosenim\\toolchains\\nim-2.2.4\\lib\\pure\\algorithm.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module algorithm", prev: framePtr, filename: "C:\\Users\\aine\\.choosenim\\toolchains\\nim-2.2.4\\lib\\pure\\algorithm.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "C:\\Users\\aine\\.choosenim\\toolchains\\nim-2.2.4\\lib\\core\\macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "C:\\Users\\aine\\.choosenim\\toolchains\\nim-2.2.4\\lib\\core\\macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module bitops_utils", prev: framePtr, filename: "C:\\Users\\aine\\.choosenim\\toolchains\\nim-2.2.4\\lib\\std\\private\\bitops_utils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module bitops_utils", prev: framePtr, filename: "C:\\Users\\aine\\.choosenim\\toolchains\\nim-2.2.4\\lib\\std\\private\\bitops_utils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module countbits_impl", prev: framePtr, filename: "C:\\Users\\aine\\.choosenim\\toolchains\\nim-2.2.4\\lib\\system\\countbits_impl.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module countbits_impl", prev: framePtr, filename: "C:\\Users\\aine\\.choosenim\\toolchains\\nim-2.2.4\\lib\\system\\countbits_impl.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module bitops", prev: framePtr, filename: "C:\\Users\\aine\\.choosenim\\toolchains\\nim-2.2.4\\lib\\pure\\bitops.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module bitops", prev: framePtr, filename: "C:\\Users\\aine\\.choosenim\\toolchains\\nim-2.2.4\\lib\\pure\\bitops.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module fenv", prev: framePtr, filename: "C:\\Users\\aine\\.choosenim\\toolchains\\nim-2.2.4\\lib\\pure\\fenv.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module fenv", prev: framePtr, filename: "C:\\Users\\aine\\.choosenim\\toolchains\\nim-2.2.4\\lib\\pure\\fenv.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module math", prev: framePtr, filename: "C:\\Users\\aine\\.choosenim\\toolchains\\nim-2.2.4\\lib\\pure\\math.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module math", prev: framePtr, filename: "C:\\Users\\aine\\.choosenim\\toolchains\\nim-2.2.4\\lib\\pure\\math.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module parseutils", prev: framePtr, filename: "C:\\Users\\aine\\.choosenim\\toolchains\\nim-2.2.4\\lib\\pure\\parseutils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module parseutils", prev: framePtr, filename: "C:\\Users\\aine\\.choosenim\\toolchains\\nim-2.2.4\\lib\\pure\\parseutils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module typetraits", prev: framePtr, filename: "C:\\Users\\aine\\.choosenim\\toolchains\\nim-2.2.4\\lib\\pure\\typetraits.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module typetraits", prev: framePtr, filename: "C:\\Users\\aine\\.choosenim\\toolchains\\nim-2.2.4\\lib\\pure\\typetraits.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module enumutils", prev: framePtr, filename: "C:\\Users\\aine\\.choosenim\\toolchains\\nim-2.2.4\\lib\\std\\enumutils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module enumutils", prev: framePtr, filename: "C:\\Users\\aine\\.choosenim\\toolchains\\nim-2.2.4\\lib\\std\\enumutils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module strbasics", prev: framePtr, filename: "C:\\Users\\aine\\.choosenim\\toolchains\\nim-2.2.4\\lib\\std\\strbasics.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module strbasics", prev: framePtr, filename: "C:\\Users\\aine\\.choosenim\\toolchains\\nim-2.2.4\\lib\\std\\strbasics.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module unicode", prev: framePtr, filename: "C:\\Users\\aine\\.choosenim\\toolchains\\nim-2.2.4\\lib\\pure\\unicode.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module unicode", prev: framePtr, filename: "C:\\Users\\aine\\.choosenim\\toolchains\\nim-2.2.4\\lib\\pure\\unicode.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module strimpl", prev: framePtr, filename: "C:\\Users\\aine\\.choosenim\\toolchains\\nim-2.2.4\\lib\\std\\private\\strimpl.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module strimpl", prev: framePtr, filename: "C:\\Users\\aine\\.choosenim\\toolchains\\nim-2.2.4\\lib\\std\\private\\strimpl.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module strutils", prev: framePtr, filename: "C:\\Users\\aine\\.choosenim\\toolchains\\nim-2.2.4\\lib\\pure\\strutils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module strutils", prev: framePtr, filename: "C:\\Users\\aine\\.choosenim\\toolchains\\nim-2.2.4\\lib\\pure\\strutils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module options", prev: framePtr, filename: "C:\\Users\\aine\\.choosenim\\toolchains\\nim-2.2.4\\lib\\pure\\options.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module options", prev: framePtr, filename: "C:\\Users\\aine\\.choosenim\\toolchains\\nim-2.2.4\\lib\\pure\\options.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jscore", prev: framePtr, filename: "C:\\Users\\aine\\.choosenim\\toolchains\\nim-2.2.4\\lib\\js\\jscore.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jscore", prev: framePtr, filename: "C:\\Users\\aine\\.choosenim\\toolchains\\nim-2.2.4\\lib\\js\\jscore.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module times", prev: framePtr, filename: "C:\\Users\\aine\\.choosenim\\toolchains\\nim-2.2.4\\lib\\pure\\times.nim", line: 0};
framePtr = F;
F.line = 1373;
F.filename = "times.nim";
if (globalThis.utcInstance_838862593 === undefined) {
  globalThis.utcInstance_838862593 = [null];
}
F.line = 1374;
if (globalThis.localInstance_838862594 === undefined) {
  globalThis.localInstance_838862594 = [null];
}
framePtr = F.prev;
var F = {procname: "module times", prev: framePtr, filename: "C:\\Users\\aine\\.choosenim\\toolchains\\nim-2.2.4\\lib\\pure\\times.nim", line: 0};
framePtr = F;
framePtr = F.prev;

function isFatPointer__system_u2878(ti_p0) {
  var result_33557312 = false;

  BeforeRet: {
    result_33557312 = !((ConstSet1[ti_p0.base.kind] != undefined));
    break BeforeRet;
  };

  return result_33557312;

}

function nimCopyAux(dest_p0, src_p1, n_p2) {
    switch (n_p2.kind) {
    case 0:
      break;
    case 1:
            dest_p0[n_p2.offset] = nimCopy(dest_p0[n_p2.offset], src_p1[n_p2.offset], n_p2.typ);
    
      break;
    case 2:
          for (var i = 0; i < n_p2.sons.length; i++) {
      nimCopyAux(dest_p0, src_p1, n_p2.sons[i]);
    }
    
      break;
    case 3:
            dest_p0[n_p2.offset] = nimCopy(dest_p0[n_p2.offset], src_p1[n_p2.offset], n_p2.typ);
      for (var i = 0; i < n_p2.sons.length; ++i) {
        nimCopyAux(dest_p0, src_p1, n_p2.sons[i][1]);
      }
    
      break;
    }

  
}
var F = {procname: "module random", prev: framePtr, filename: "C:\\Users\\aine\\.choosenim\\toolchains\\nim-2.2.4\\lib\\pure\\random.nim", line: 0};
framePtr = F;
F.line = 116;
F.filename = "random.nim";
var state_671088655 = [nimCopy(null, DefaultRandSeed_671088654, NTI671088644)];
framePtr = F.prev;
var F = {procname: "module random", prev: framePtr, filename: "C:\\Users\\aine\\.choosenim\\toolchains\\nim-2.2.4\\lib\\pure\\random.nim", line: 0};
framePtr = F;
framePtr = F.prev;

function toFloat__system_u1572(i_p0) {
  var result_33556006 = 0.0;

  var F = {procname: "system.toFloat", prev: framePtr, filename: "C:\\Users\\aine\\.choosenim\\toolchains\\nim-2.2.4\\lib\\system.nim", line: 0};
  framePtr = F;
    F.line = 1290;
    F.filename = "system.nim";
    result_33556006 = i_p0;
  framePtr = F.prev;

  return result_33556006;

}

function HEX2F__system_u1584(x_p0, y_p1) {
  var result_33556019 = 0.0;

  var F = {procname: "system./", prev: framePtr, filename: "C:\\Users\\aine\\.choosenim\\toolchains\\nim-2.2.4\\lib\\system.nim", line: 0};
  framePtr = F;
    F.line = 1338;
    F.filename = "system.nim";
    result_33556019 = (toFloat__system_u1572(x_p0) / toFloat__system_u1572(y_p1));
  framePtr = F.prev;

  return result_33556019;

}

function epochTime__pureZtimes_u4759() {
  var result_838865560 = 0.0;

  var F = {procname: "times.epochTime", prev: framePtr, filename: "C:\\Users\\aine\\.choosenim\\toolchains\\nim-2.2.4\\lib\\pure\\times.nim", line: 0};
  framePtr = F;
    F.line = 2799;
    F.filename = "times.nim";
    result_838865560 = HEX2F__system_u1584(new Date().getTime(), 1000);
  framePtr = F.prev;

  return result_838865560;

}

function add__system_u1942(x_p0, x_p0_Idx, y_p1) {
          if (x_p0[x_p0_Idx] === null) { x_p0[x_p0_Idx] = []; }
      var off = x_p0[x_p0_Idx].length;
      x_p0[x_p0_Idx].length += y_p1.length;
      for (var i = 0; i < y_p1.length; ++i) {
        x_p0[x_p0_Idx][off+i] = y_p1.charCodeAt(i);
      }
    

  
}

function auxWriteStackTrace__system_u2084(f_p0) {
  var result_33556518 = [[]];

    var it_33556526 = f_p0;
    var i_33556527 = 0;
    var total_33556528 = 0;
    var tempFrames_33556529 = arrayConstr(64, {Field0: null, Field1: 0, Field2: null}, NTI33555836);
    Label1: {
        Label2: while (true) {
        if (!(!((it_33556526 == null)) && (i_33556527 <= 63))) break Label2;
          tempFrames_33556529[i_33556527].Field0 = it_33556526.procname;
          tempFrames_33556529[i_33556527].Field1 = it_33556526.line;
          tempFrames_33556529[i_33556527].Field2 = it_33556526.filename;
          i_33556527 += 1;
          total_33556528 += 1;
          it_33556526 = it_33556526.prev;
        }
    };
    Label3: {
        Label4: while (true) {
        if (!!((it_33556526 == null))) break Label4;
          total_33556528 += 1;
          it_33556526 = it_33556526.prev;
        }
    };
    result_33556518[0] = nimCopy(null, [], NTI33554449);
    if (!((total_33556528 == i_33556527))) {
    result_33556518[0].push.apply(result_33556518[0], [40]);;
    result_33556518[0].push.apply(result_33556518[0], HEX24__systemZdollars_u14((total_33556528 - i_33556527)));;
    result_33556518[0].push.apply(result_33556518[0], [32,99,97,108,108,115,32,111,109,105,116,116,101,100,41,32,46,46,46,10]);;
    }
    
    Label5: {
      var j_33556562 = 0;
      var colontmp__536871439 = 0;
      colontmp__536871439 = (i_33556527 - 1);
      var res_536871441 = colontmp__536871439;
      Label6: {
          Label7: while (true) {
          if (!(0 <= res_536871441)) break Label7;
            j_33556562 = res_536871441;
            result_33556518[0].push.apply(result_33556518[0], cstrToNimstr(tempFrames_33556529[j_33556562].Field2));;
            if ((0 < tempFrames_33556529[j_33556562].Field1)) {
            result_33556518[0].push.apply(result_33556518[0], [40]);;
            addInt__stdZprivateZdigitsutils_u241(result_33556518, 0, tempFrames_33556529[j_33556562].Field1);
            if (false) {
            result_33556518[0].push.apply(result_33556518[0], [44,32]);;
            addInt__stdZprivateZdigitsutils_u241(result_33556518, 0, 0);
            }
            
            result_33556518[0].push.apply(result_33556518[0], [41]);;
            }
            
            result_33556518[0].push.apply(result_33556518[0], [32,97,116,32]);;
            add__system_u1942(result_33556518, 0, tempFrames_33556529[j_33556562].Field0);
            result_33556518[0].push.apply(result_33556518[0], [10]);;
            res_536871441 -= 1;
          }
      };
    };

  return result_33556518[0];

}

function rawWriteStackTrace__system_u2180() {
  var result_33556613 = [];

    if (!((framePtr == null))) {
    result_33556613 = nimCopy(null, ([84,114,97,99,101,98,97,99,107,32,40,109,111,115,116,32,114,101,99,101,110,116,32,99,97,108,108,32,108,97,115,116,41,10]).concat(auxWriteStackTrace__system_u2084(framePtr)), NTI33554449);
    }
    else {
      result_33556613 = nimCopy(null, [78,111,32,115,116,97,99,107,32,116,114,97,99,101,98,97,99,107,32,97,118,97,105,108,97,98,108,101,10], NTI33554449);
    }
    

  return result_33556613;

}

function newSeq__system_u2516(len_p0) {
  var result_33556952 = [];

  var F = {procname: "newSeq.newSeq", prev: framePtr, filename: "C:\\Users\\aine\\.choosenim\\toolchains\\nim-2.2.4\\lib\\system.nim", line: 0};
  framePtr = F;
    F.line = 651;
    F.filename = "system.nim";
    result_33556952 = new Array(len_p0); for (var i = 0 ; i < len_p0 ; ++i) { result_33556952[i] = null; }  framePtr = F.prev;

  return result_33556952;

}

function isNimException__system_u2017() {
    return lastJSError && lastJSError.m_type;

  
}

function getCurrentException() {
  var result_33556452 = null;

    if (isNimException__system_u2017()) {
    result_33556452 = lastJSError;
    }
    

  return result_33556452;

}

function raiseDefect() {
    if (isNimException__system_u2017()) {
    var e_33556664 = getCurrentException();
    if (isObj(e_33556664.m_type, NTI33555172)) {
    if ((excHandler == 0)) {
    unhandledException(e_33556664);
    }
    
    e_33556664.trace = nimCopy(null, rawWriteStackTrace__system_u2180(), NTI33554449);
    throw e_33556664;
    }
    
    }
    

  
}

function unhandledException(e_p0) {
    var buf_33556658 = [[]];
    if (!(((e_p0.message).length == 0))) {
    buf_33556658[0].push.apply(buf_33556658[0], [69,114,114,111,114,58,32,117,110,104,97,110,100,108,101,100,32,101,120,99,101,112,116,105,111,110,58,32]);;
    buf_33556658[0].push.apply(buf_33556658[0], e_p0.message);;
    }
    else {
    buf_33556658[0].push.apply(buf_33556658[0], [69,114,114,111,114,58,32,117,110,104,97,110,100,108,101,100,32,101,120,99,101,112,116,105,111,110]);;
    }
    
    buf_33556658[0].push.apply(buf_33556658[0], [32,91]);;
    add__system_u1942(buf_33556658, 0, e_p0.name);
    buf_33556658[0].push.apply(buf_33556658[0], [93,10]);;
    buf_33556658[0].push.apply(buf_33556658[0], rawWriteStackTrace__system_u2180());;
    var cbuf_33556659 = toJSStr(buf_33556658[0]);
    framePtr = null;
      if (typeof(Error) !== "undefined") {
    throw new Error(cbuf_33556659);
  }
  else {
    throw cbuf_33556659;
  }
  

  
}

function raiseOverflow() {
    raiseException({message: [111,118,101,114,45,32,111,114,32,117,110,100,101,114,102,108,111,119], parent: null, m_type: NTI134217743, name: null, trace: [], up: null}, "OverflowDefect");

  
}

function checkOverflowInt(a_p0) {
        if (a_p0 > 2147483647 || a_p0 < -2147483648) raiseOverflow();
  

  
}

function raiseRangeError() {
    raiseException({message: [118,97,108,117,101,32,111,117,116,32,111,102,32,114,97,110,103,101], parent: null, m_type: NTI134217751, name: null, trace: [], up: null}, "RangeDefect");

  
}

function addChars__stdZprivateZdigitsutils_u202(result_p0, result_p0_Idx, x_p1, start_p2, n_p3) {
    var Temporary1;

  var F = {procname: "addChars.addChars", prev: framePtr, filename: "C:\\Users\\aine\\.choosenim\\toolchains\\nim-2.2.4\\lib\\std\\private\\digitsutils.nim", line: 0};
  framePtr = F;
    F.line = 44;
    F.filename = "digitsutils.nim";
    var old_301990096 = (result_p0[result_p0_Idx]).length;
    F.line = 45;
    if (result_p0[result_p0_Idx].length < (Temporary1 = chckRange(addInt(old_301990096, n_p3), 0, 2147483647), Temporary1)) { for (var i = result_p0[result_p0_Idx].length; i < Temporary1; ++i) result_p0[result_p0_Idx].push(0); }
         else {result_p0[result_p0_Idx].length = Temporary1; };
    Label2: {
      F.line = 47;
      var iHEX60gensym4_301990110 = 0;
      F.line = 128;
      F.filename = "iterators_1.nim";
      var i_536871434 = 0;
      Label3: {
        F.line = 129;
          Label4: while (true) {
          if (!(i_536871434 < n_p3)) break Label4;
            F.line = 50;
            F.filename = "digitsutils.nim";
            iHEX60gensym4_301990110 = i_536871434;
            F.line = 47;
            result_p0[result_p0_Idx][chckIndx(addInt(old_301990096, iHEX60gensym4_301990110), 0, (result_p0[result_p0_Idx]).length - 1)] = x_p1.charCodeAt(chckIndx(addInt(start_p2, iHEX60gensym4_301990110), 0, (x_p1).length - 1));
            F.line = 131;
            F.filename = "iterators_1.nim";
            i_536871434 = addInt(i_536871434, 1);
          }
      };
    };
  framePtr = F.prev;

  
}

function addChars__stdZprivateZdigitsutils_u198(result_p0, result_p0_Idx, x_p1) {
  var F = {procname: "addChars.addChars", prev: framePtr, filename: "C:\\Users\\aine\\.choosenim\\toolchains\\nim-2.2.4\\lib\\std\\private\\digitsutils.nim", line: 0};
  framePtr = F;
    F.line = 56;
    F.filename = "digitsutils.nim";
    addChars__stdZprivateZdigitsutils_u202(result_p0, result_p0_Idx, x_p1, 0, ((x_p1) == null ? 0 : (x_p1).length));
  framePtr = F.prev;

  
}

function addInt__stdZprivateZdigitsutils_u223(result_p0, result_p0_Idx, x_p1) {
  var F = {procname: "digitsutils.addInt", prev: framePtr, filename: "C:\\Users\\aine\\.choosenim\\toolchains\\nim-2.2.4\\lib\\std\\private\\digitsutils.nim", line: 0};
  framePtr = F;
    F.line = 112;
    F.filename = "digitsutils.nim";
    addChars__stdZprivateZdigitsutils_u198(result_p0, result_p0_Idx, ((x_p1) + ""));
  framePtr = F.prev;

  
}

function addInt__stdZprivateZdigitsutils_u241(result_p0, result_p0_Idx, x_p1) {
  var F = {procname: "digitsutils.addInt", prev: framePtr, filename: "C:\\Users\\aine\\.choosenim\\toolchains\\nim-2.2.4\\lib\\std\\private\\digitsutils.nim", line: 0};
  framePtr = F;
    F.line = 116;
    F.filename = "digitsutils.nim";
    addInt__stdZprivateZdigitsutils_u223(result_p0, result_p0_Idx, BigInt(x_p1));
  framePtr = F.prev;

  
}

function HEX24__systemZdollars_u14(xHEX60gensym0_p0) {
  var result_369098768 = [[]];

  var F = {procname: "dollars.$", prev: framePtr, filename: "C:\\Users\\aine\\.choosenim\\toolchains\\nim-2.2.4\\lib\\system\\dollars.nim", line: 0};
  framePtr = F;
    F.line = 20;
    F.filename = "dollars.nim";
    result_369098768[0] = nimCopy(null, [], NTI33554449);
    F.line = 21;
    addInt__stdZprivateZdigitsutils_u241(result_369098768, 0, xHEX60gensym0_p0);
  framePtr = F.prev;

  return result_369098768[0];

}

function raiseIndexError(i_p0, a_p1, b_p2) {
    var Temporary1;

    if ((b_p2 < a_p1)) {
    Temporary1 = [105,110,100,101,120,32,111,117,116,32,111,102,32,98,111,117,110,100,115,44,32,116,104,101,32,99,111,110,116,97,105,110,101,114,32,105,115,32,101,109,112,116,121];
    }
    else {
    Temporary1 = ([105,110,100,101,120,32]).concat(HEX24__systemZdollars_u14(i_p0),[32,110,111,116,32,105,110,32],HEX24__systemZdollars_u14(a_p1),[32,46,46,32],HEX24__systemZdollars_u14(b_p2));
    }
    
    raiseException({message: nimCopy(null, Temporary1, NTI33554449), parent: null, m_type: NTI134217749, name: null, trace: [], up: null}, "IndexDefect");

  
}

function rotl__pureZrandom_u24(x_p0, k_p1) {
  var result_671088667 = 0n;

  var F = {procname: "random.rotl", prev: framePtr, filename: "C:\\Users\\aine\\.choosenim\\toolchains\\nim-2.2.4\\lib\\pure\\random.nim", line: 0};
  framePtr = F;
    F.line = 136;
    F.filename = "random.nim";
    result_671088667 = (BigInt.asUintN(64, x_p0 << BigInt(k_p1)) | (x_p0 >> BigInt(BigInt.asUintN(64, (64n - k_p1)))));
  framePtr = F.prev;

  return result_671088667;

}

function next__pureZrandom_u36(r_p0) {
  var result_671088678 = 0n;

  var F = {procname: "random.next", prev: framePtr, filename: "C:\\Users\\aine\\.choosenim\\toolchains\\nim-2.2.4\\lib\\pure\\random.nim", line: 0};
  framePtr = F;
    F.line = 154;
    F.filename = "random.nim";
    var s0_671088679 = r_p0.a0;
    F.line = 155;
    var s1_671088680 = r_p0.a1;
    F.line = 156;
    result_671088678 = BigInt.asUintN(64, (s0_671088679 + s1_671088680));
    F.line = 157;
    s1_671088680 = (s1_671088680 ^ s0_671088679);
    F.line = 158;
    r_p0.a0 = ((rotl__pureZrandom_u24(s0_671088679, 55n) ^ s1_671088680) ^ BigInt.asUintN(64, s1_671088680 << BigInt(14)));
    F.line = 159;
    r_p0.a1 = rotl__pureZrandom_u24(s1_671088680, 36n);
  framePtr = F.prev;

  return result_671088678;

}

function skipRandomNumbers__pureZrandom_u45(s_p0) {
  var F = {procname: "random.skipRandomNumbers", prev: framePtr, filename: "C:\\Users\\aine\\.choosenim\\toolchains\\nim-2.2.4\\lib\\pure\\random.nim", line: 0};
  framePtr = F;
    F.line = 218;
    F.filename = "random.nim";
    var s0_671088688 = 0n;
    F.line = 219;
    var s1_671088689 = 0n;
    Label1: {
      F.line = 220;
      var i_671088698 = 0;
      F.line = 96;
      F.filename = "iterators_1.nim";
      var res_536871428 = 0;
      Label2: {
        F.line = 97;
          Label3: while (true) {
          if (!(res_536871428 <= 1)) break Label3;
            F.line = 220;
            F.filename = "random.nim";
            i_671088698 = res_536871428;
            Label4: {
              F.line = 221;
              var b_671088703 = 0;
              F.line = 128;
              F.filename = "iterators_1.nim";
              var i_536871426 = 0;
              Label5: {
                F.line = 129;
                  Label6: while (true) {
                  if (!(i_536871426 < 64)) break Label6;
                    F.line = 221;
                    F.filename = "random.nim";
                    b_671088703 = i_536871426;
                    if (!(((helper_671088687[chckIndx(i_671088698, 0, (helper_671088687).length - 1)] & BigInt.asUintN(64, 1n << BigInt(BigInt.asUintN(64, BigInt(b_671088703))))) == 0n))) {
                    F.line = 223;
                    s0_671088688 = (s0_671088688 ^ s_p0.a0);
                    F.line = 224;
                    s1_671088689 = (s1_671088689 ^ s_p0.a1);
                    }
                    
                    F.line = 225;
                    (next__pureZrandom_u36(s_p0));
                    F.line = 131;
                    F.filename = "iterators_1.nim";
                    i_536871426 = addInt(i_536871426, 1);
                  }
              };
            };
            F.line = 102;
            res_536871428 = addInt(res_536871428, 1);
          }
      };
    };
    F.line = 226;
    F.filename = "random.nim";
    s_p0.a0 = s0_671088688;
    F.line = 227;
    s_p0.a1 = s1_671088689;
  framePtr = F.prev;

  
}

function initRand__pureZrandom_u250(seed_p0) {
    var Temporary1;

  var result_671088892 = [({a0: 0n, a1: 0n})];

  var F = {procname: "random.initRand", prev: framePtr, filename: "C:\\Users\\aine\\.choosenim\\toolchains\\nim-2.2.4\\lib\\pure\\random.nim", line: 0};
  framePtr = F;
    F.line = 606;
    F.filename = "random.nim";
    if (!((seed_p0 == 0n))) {
    Temporary1 = seed_p0;
    }
    else {
    Temporary1 = 2147483647n;
    }
    
    var seed_671088898 = Temporary1;
    F.line = 607;
    result_671088892[0] = nimCopy(result_671088892[0], {a0: BigInt.asUintN(64, (seed_671088898 >> BigInt(16))), a1: BigInt.asUintN(64, (seed_671088898 & 65535n))}, NTI671088644);
    F.line = 611;
    skipRandomNumbers__pureZrandom_u45(result_671088892[0]);
    F.line = 612;
    (next__pureZrandom_u36(result_671088892[0]));
  framePtr = F.prev;

  return result_671088892[0];

}

function initRand__pureZrandom_u292() {
  var result_671088933 = ({a0: 0n, a1: 0n});

  var F = {procname: "random.initRand", prev: framePtr, filename: "C:\\Users\\aine\\.choosenim\\toolchains\\nim-2.2.4\\lib\\pure\\random.nim", line: 0};
  framePtr = F;
    F.line = 698;
    F.filename = "random.nim";
    var time_671088934 = (BigInt(Math.trunc((epochTime__pureZtimes_u4759() * 1000.0))) & 2147483647n);
    F.line = 699;
    result_671088933 = nimCopy(result_671088933, initRand__pureZrandom_u250(time_671088934), NTI671088644);
  framePtr = F.prev;

  return result_671088933;

}

function randomize__pureZrandom_u299() {
  var F = {procname: "random.randomize", prev: framePtr, filename: "C:\\Users\\aine\\.choosenim\\toolchains\\nim-2.2.4\\lib\\pure\\random.nim", line: 0};
  framePtr = F;
    F.line = 753;
    F.filename = "random.nim";
    state_671088655[0] = nimCopy(state_671088655[0], initRand__pureZrandom_u292(), NTI671088644);
  framePtr = F.prev;

  
}

function sysFatal__stdZassertions_u44(message_p1) {
  var F = {procname: "sysFatal.sysFatal", prev: framePtr, filename: "C:\\Users\\aine\\.choosenim\\toolchains\\nim-2.2.4\\lib\\system\\fatal.nim", line: 0};
  framePtr = F;
    F.line = 53;
    F.filename = "fatal.nim";
    raiseException({message: nimCopy(null, message_p1, NTI33554449), m_type: NTI134217745, parent: null, name: null, trace: [], up: null}, "AssertionDefect");
  framePtr = F.prev;

  
}

function raiseAssert__stdZassertions_u42(msg_p0) {
  var F = {procname: "assertions.raiseAssert", prev: framePtr, filename: "C:\\Users\\aine\\.choosenim\\toolchains\\nim-2.2.4\\lib\\std\\assertions.nim", line: 0};
  framePtr = F;
    F.line = 36;
    F.filename = "assertions.nim";
    sysFatal__stdZassertions_u44(msg_p0);
  framePtr = F.prev;

  
}

function failedAssertImpl__stdZassertions_u84(msg_p0) {
  var F = {procname: "assertions.failedAssertImpl", prev: framePtr, filename: "C:\\Users\\aine\\.choosenim\\toolchains\\nim-2.2.4\\lib\\std\\assertions.nim", line: 0};
  framePtr = F;
    F.line = 41;
    F.filename = "assertions.nim";
    raiseAssert__stdZassertions_u42(msg_p0);
  framePtr = F.prev;

  
}

function rand__pureZrandom_u112(r_p0, max_p1) {
  var result_671088756 = 0n;

  var F = {procname: "rand.rand", prev: framePtr, filename: "C:\\Users\\aine\\.choosenim\\toolchains\\nim-2.2.4\\lib\\pure\\random.nim", line: 0};
  framePtr = F;
  BeforeRet: {
    if ((max_p1 == 0n)) {
    F.line = 231;
    F.filename = "random.nim";
    break BeforeRet;
    }
    else {
      F.line = 233;
      var max_671088757 = max_p1;
      if ((max_671088757 == 18446744073709551615n)) {
      F.line = 235;
      result_671088756 = next__pureZrandom_u36(r_p0);
      break BeforeRet;
      }
      
      F.line = 236;
      var iters_671088770 = 0;
      Label1: {
        F.line = 237;
          Label2: while (true) {
          if (!true) break Label2;
            F.line = 238;
            var x_671088771 = next__pureZrandom_u36(r_p0);
            if (((x_671088771 <= BigInt.asUintN(64, (18446744073709551615n - (18446744073709551615n % max_671088757)))) || (20 < iters_671088770))) {
            F.line = 241;
            result_671088756 = (x_671088771 % BigInt.asUintN(64, (max_671088757 + 1n)));
            break BeforeRet;
            }
            else {
              F.line = 243;
            iters_671088770 = addInt(iters_671088770, 1);
            }
            
          }
      };
    }
    
  };
  framePtr = F.prev;

  return result_671088756;

}

function rand__dungeon_u67(r_p0, x_p1) {
  var result_536870983 = 0;

  var F = {procname: "rand.rand", prev: framePtr, filename: "C:\\Users\\aine\\.choosenim\\toolchains\\nim-2.2.4\\lib\\pure\\random.nim", line: 0};
  framePtr = F;
    if (!((x_p1.a <= x_p1.b))) {
    F.line = 347;
    F.filename = "random.nim";
    failedAssertImpl__stdZassertions_u84(makeNimstrLit("C:\\Users\\aine\\.choosenim\\toolchains\\nim-2.2.4\\lib\\pure\\random.nim(347, 3) `x.a <= x.b` "));
    }
    
    F.line = 354;
    result_536870983 = Number(BigInt.asIntN(32, BigInt.asUintN(64, (rand__pureZrandom_u112(r_p0, BigInt.asUintN(64, (BigInt.asUintN(64, BigInt(x_p1.b)) - BigInt.asUintN(64, BigInt(x_p1.a))))) + BigInt.asUintN(64, BigInt(x_p1.a))))));
  framePtr = F.prev;

  return result_536870983;

}

function rand__dungeon_u59(x_p0) {
  var result_536870974 = 0;

  var F = {procname: "rand.rand", prev: framePtr, filename: "C:\\Users\\aine\\.choosenim\\toolchains\\nim-2.2.4\\lib\\pure\\random.nim", line: 0};
  framePtr = F;
    F.line = 376;
    F.filename = "random.nim";
    result_536870974 = rand__dungeon_u67(state_671088655[0], x_p0);
  framePtr = F.prev;

  return result_536870974;

}

function HEX2EHEX2E__stdZstrbasics_u48(a_p0, b_p1) {
  var result_939524149 = ({a: 0, b: 0});

  var F = {procname: ".....", prev: framePtr, filename: "C:\\Users\\aine\\.choosenim\\toolchains\\nim-2.2.4\\lib\\system.nim", line: 0};
  framePtr = F;
    F.line = 436;
    F.filename = "system.nim";
    result_939524149 = nimCopy(result_939524149, {a: a_p0, b: b_p1}, NTI687866351);
  framePtr = F.prev;

  return result_939524149;

}

function getRandomInt(max_p0) {
  var result_536870955 = 0;

  var F = {procname: "dungeon.getRandomInt", prev: framePtr, filename: "D:\\tribenine\\24tribe.github.io\\src\\dungeon.nim", line: 0};
  framePtr = F;
    F.line = 48;
    F.filename = "dungeon.nim";
    result_536870955 = rand__dungeon_u59(HEX2EHEX2E__stdZstrbasics_u48(0, subInt(max_p0, 1)));
  framePtr = F.prev;

  return result_536870955;

}

function createGrid(gridWidth_p0, gridHeight_p1) {
  var result_536870997 = [];

  var F = {procname: "dungeon.createGrid", prev: framePtr, filename: "D:\\tribenine\\24tribe.github.io\\src\\dungeon.nim", line: 0};
  framePtr = F;
    Label1: {
      F.line = 52;
      F.filename = "dungeon.nim";
      var y_536871002 = 0;
      F.line = 128;
      F.filename = "iterators_1.nim";
      var i_536871451 = 0;
      Label2: {
        F.line = 129;
          Label3: while (true) {
          if (!(i_536871451 < gridHeight_p1)) break Label3;
            F.line = 52;
            F.filename = "dungeon.nim";
            y_536871002 = i_536871451;
            F.line = 53;
            var row_536871023 = newSeq__system_u2516(0);
            Label4: {
              F.line = 55;
              var x_536871028 = 0;
              F.line = 128;
              F.filename = "iterators_1.nim";
              var i_536871449 = 0;
              Label5: {
                F.line = 129;
                  Label6: while (true) {
                  if (!(i_536871449 < gridWidth_p0)) break Label6;
                    F.line = 55;
                    F.filename = "dungeon.nim";
                    x_536871028 = i_536871449;
                    F.line = 56;
                    row_536871023.push("N");;
                    F.line = 131;
                    F.filename = "iterators_1.nim";
                    i_536871449 = addInt(i_536871449, 1);
                  }
              };
            };
            F.line = 58;
            F.filename = "dungeon.nim";
            var Temporary7 = nimCopy(null, row_536871023, NTI33556097);
            result_536870997.push(Temporary7);;
            F.line = 131;
            F.filename = "iterators_1.nim";
            i_536871451 = addInt(i_536871451, 1);
          }
      };
    };
  framePtr = F.prev;

  return result_536870997;

}

function contains__pureZtimes_u1783(s_p0, value_p1) {
  var result_838862589 = false;

  var F = {procname: "contains.contains", prev: framePtr, filename: "C:\\Users\\aine\\.choosenim\\toolchains\\nim-2.2.4\\lib\\system.nim", line: 0};
  framePtr = F;
    F.line = 752;
    F.filename = "system.nim";
    result_838862589 = ((s_p0.a <= value_p1) && (value_p1 <= s_p0.b));
  framePtr = F.prev;

  return result_838862589;

}

function validPosition__dungeon_u181(grid_p0, x_p1, y_p2) {
  var result_536871097 = false;

  var F = {procname: "dungeon.validPosition", prev: framePtr, filename: "D:\\tribenine\\24tribe.github.io\\src\\dungeon.nim", line: 0};
  framePtr = F;
    F.line = 71;
    F.filename = "dungeon.nim";
    var gridHeight_536871102 = (grid_p0).length;
    F.line = 72;
    var gridWidth_536871107 = (grid_p0[chckIndx(0, 0, (grid_p0).length - 1)]).length;
    F.line = 73;
    result_536871097 = (contains__pureZtimes_u1783(HEX2EHEX2E__stdZstrbasics_u48(0, subInt(gridWidth_536871107, 1)), x_p1) && contains__pureZtimes_u1783(HEX2EHEX2E__stdZstrbasics_u48(0, subInt(gridHeight_536871102, 1)), y_p2));
  framePtr = F.prev;

  return result_536871097;

}

function setIfValidPos__dungeon_u285(grid_p0, grid_p0_Idx, x_p1, y_p2, val_p3) {
  var F = {procname: "dungeon.setIfValidPos", prev: framePtr, filename: "D:\\tribenine\\24tribe.github.io\\src\\dungeon.nim", line: 0};
  framePtr = F;
    if (validPosition__dungeon_u181(grid_p0[grid_p0_Idx], x_p1, y_p2)) {
    F.line = 89;
    F.filename = "dungeon.nim";
    grid_p0[grid_p0_Idx][chckIndx(y_p2, 0, (grid_p0[grid_p0_Idx]).length - 1)][chckIndx(x_p1, 0, (grid_p0[grid_p0_Idx][chckIndx(y_p2, 0, (grid_p0[grid_p0_Idx]).length - 1)]).length - 1)] = val_p3;
    }
    
  framePtr = F.prev;

  
}

function getNeighbourPositions__dungeon_u125(x_p0, y_p1) {
  var result_536871040 = [];

  var F = {procname: "dungeon.getNeighbourPositions", prev: framePtr, filename: "D:\\tribenine\\24tribe.github.io\\src\\dungeon.nim", line: 0};
  framePtr = F;
    F.line = 62;
    F.filename = "dungeon.nim";
    result_536871040 = nimCopy(null, [new Int32Array([subInt(x_p0, 1), y_p1]), new Int32Array([addInt(x_p0, 1), y_p1]), new Int32Array([x_p0, addInt(y_p1, 1)]), new Int32Array([x_p0, subInt(y_p1, 1)])], NTI536871015);
  framePtr = F.prev;

  return result_536871040;

}

function getPossibleNextPositions__dungeon_u234(x_p0, y_p1, grid_p2) {
  var result_536871150 = [];

  var F = {procname: "dungeon.getPossibleNextPositions", prev: framePtr, filename: "D:\\tribenine\\24tribe.github.io\\src\\dungeon.nim", line: 0};
  framePtr = F;
    Label1: {
      F.line = 77;
      F.filename = "dungeon.nim";
      var pos_536871173 = new Int32Array(2);
      F.line = 247;
      F.filename = "iterators.nim";
      var colontmp__536871456 = [];
      F.line = 77;
      F.filename = "dungeon.nim";
      colontmp__536871456 = getNeighbourPositions__dungeon_u125(x_p0, y_p1);
      F.line = 249;
      F.filename = "iterators.nim";
      var i_536871458 = 0;
      F.line = 250;
      var L_536871459 = (colontmp__536871456).length;
      Label2: {
        F.line = 251;
          Label3: while (true) {
          if (!(i_536871458 < L_536871459)) break Label3;
            F.line = 77;
            F.filename = "dungeon.nim";
            pos_536871173 = colontmp__536871456[chckIndx(i_536871458, 0, (colontmp__536871456).length - 1)];
            F.line = 78;
            var neightbourX_536871174 = pos_536871173[chckIndx(0, 0, (pos_536871173).length - 1)];
            F.line = 79;
            var neightbourY_536871175 = pos_536871173[chckIndx(1, 0, (pos_536871173).length - 1)];
            if (validPosition__dungeon_u181(grid_p2, neightbourX_536871174, neightbourY_536871175)) {
            F.line = 82;
            var node_536871176 = grid_p2[chckIndx(neightbourY_536871175, 0, (grid_p2).length - 1)][chckIndx(neightbourX_536871174, 0, (grid_p2[chckIndx(neightbourY_536871175, 0, (grid_p2).length - 1)]).length - 1)];
            if (((node_536871176 == "N") || (node_536871176 == "O"))) {
            F.line = 84;
            var Temporary4 = nimCopy(null, pos_536871173, NTI536870919);
            result_536871150.push(Temporary4);;
            }
            
            }
            
            F.line = 13;
            F.filename = "iterators.nim";
            i_536871458 += 1;
            if (!(((colontmp__536871456).length == L_536871459))) {
            F.line = 254;
            failedAssertImpl__stdZassertions_u84(makeNimstrLit("C:\\Users\\aine\\.choosenim\\toolchains\\nim-2.2.4\\lib\\system\\iterators.nim(254, 11) `len(a) == L` the length of the seq changed while iterating over it"));
            }
            
          }
      };
    };
  framePtr = F.prev;

  return result_536871150;

}

function pop__dungeon_u309(s_p0, s_p0_Idx) {
  var result_536871224 = new Int32Array(2);

  var F = {procname: "pop.pop", prev: framePtr, filename: "C:\\Users\\aine\\.choosenim\\toolchains\\nim-2.2.4\\lib\\system.nim", line: 0};
  framePtr = F;
    F.line = 1790;
    F.filename = "system.nim";
    var L_536871228 = subInt((s_p0[s_p0_Idx]).length, 1);
    F.line = 1795;
    result_536871224 = nimCopy(result_536871224, s_p0[s_p0_Idx][chckIndx(L_536871228, 0, (s_p0[s_p0_Idx]).length - 1)], NTI536870919);
    F.line = 1796;
    if (s_p0[s_p0_Idx].length < chckRange(L_536871228, 0, 2147483647)) { for (var i = s_p0[s_p0_Idx].length ; i < chckRange(L_536871228, 0, 2147483647) ; ++i) s_p0[s_p0_Idx].push(new Int32Array(2)); }
               else { s_p0[s_p0_Idx].length = chckRange(L_536871228, 0, 2147483647); };
  framePtr = F.prev;

  return result_536871224;

}

function getPath(gridWidth_p0, gridHeight_p1) {
  var result_536871205 = [[]];

  var F = {procname: "dungeon.getPath", prev: framePtr, filename: "D:\\tribenine\\24tribe.github.io\\src\\dungeon.nim", line: 0};
  framePtr = F;
    F.line = 93;
    F.filename = "dungeon.nim";
    var grid_536871206 = [createGrid(gridWidth_p0, gridHeight_p1)];
    F.line = 95;
    var objX_536871207 = getRandomInt(gridWidth_p0);
    F.line = 96;
    var objY_536871208 = 0;
    F.line = 97;
    var startX_536871209 = getRandomInt(gridWidth_p0);
    F.line = 98;
    var startY_536871210 = subInt(gridHeight_p1, 1);
    F.line = 100;
    setIfValidPos__dungeon_u285(grid_536871206, 0, subInt(objX_536871207, 1), objY_536871208, "V");
    F.line = 101;
    setIfValidPos__dungeon_u285(grid_536871206, 0, addInt(objX_536871207, 1), objY_536871208, "V");
    F.line = 102;
    grid_536871206[0][chckIndx(objY_536871208, 0, (grid_536871206[0]).length - 1)][chckIndx(objX_536871207, 0, (grid_536871206[0][chckIndx(objY_536871208, 0, (grid_536871206[0]).length - 1)]).length - 1)] = "O";
    F.line = 104;
    grid_536871206[0][chckIndx(startY_536871210, 0, (grid_536871206[0]).length - 1)][chckIndx(startX_536871209, 0, (grid_536871206[0][chckIndx(startY_536871210, 0, (grid_536871206[0]).length - 1)]).length - 1)] = "V";
    F.line = 105;
    setIfValidPos__dungeon_u285(grid_536871206, 0, subInt(startX_536871209, 1), startY_536871210, "V");
    F.line = 106;
    setIfValidPos__dungeon_u285(grid_536871206, 0, addInt(startX_536871209, 1), startY_536871210, "V");
    F.line = 108;
    result_536871205[0].push(new Int32Array([startX_536871209, startY_536871210]));;
    F.line = 110;
    var x_536871215 = startX_536871209;
    F.line = 111;
    var y_536871216 = startY_536871210;
    Label1: {
      F.line = 113;
        Label2: while (true) {
        if (!!((grid_536871206[0][chckIndx(y_536871216, 0, (grid_536871206[0]).length - 1)][chckIndx(x_536871215, 0, (grid_536871206[0][chckIndx(y_536871216, 0, (grid_536871206[0]).length - 1)]).length - 1)] == "O"))) break Label2;
          Label3: {
            F.line = 114;
            var nextPositions_536871217 = getPossibleNextPositions__dungeon_u234(x_536871215, y_536871216, grid_536871206[0]);
            if (((nextPositions_536871217).length == 0)) {
            F.line = 117;
            (pop__dungeon_u309(result_536871205, 0));
            F.line = 118;
            var lastPos_536871236 = nimCopy(null, result_536871205[0][chckIndx(subInt((result_536871205[0]).length, 1), 0, (result_536871205[0]).length - 1)], NTI536870919);
            F.line = 119;
            x_536871215 = lastPos_536871236[chckIndx(0, 0, (lastPos_536871236).length - 1)];
            F.line = 120;
            y_536871216 = lastPos_536871236[chckIndx(1, 0, (lastPos_536871236).length - 1)];
            F.line = 121;
            break Label3;
            }
            
            F.line = 123;
            var nextPos_536871240 = nimCopy(null, nextPositions_536871217[chckIndx(getRandomInt((nextPositions_536871217).length), 0, (nextPositions_536871217).length - 1)], NTI536870919);
            F.line = 124;
            var nextPosX_536871241 = nextPos_536871240[chckIndx(0, 0, (nextPos_536871240).length - 1)];
            F.line = 125;
            var nextPosY_536871242 = nextPos_536871240[chckIndx(1, 0, (nextPos_536871240).length - 1)];
            if (!((grid_536871206[0][chckIndx(nextPosY_536871242, 0, (grid_536871206[0]).length - 1)][chckIndx(nextPosX_536871241, 0, (grid_536871206[0][chckIndx(nextPosY_536871242, 0, (grid_536871206[0]).length - 1)]).length - 1)] == "O"))) {
            F.line = 128;
            grid_536871206[0][chckIndx(nextPosY_536871242, 0, (grid_536871206[0]).length - 1)][chckIndx(nextPosX_536871241, 0, (grid_536871206[0][chckIndx(nextPosY_536871242, 0, (grid_536871206[0]).length - 1)]).length - 1)] = "V";
            }
            
            F.line = 130;
            x_536871215 = nextPosX_536871241;
            F.line = 131;
            y_536871216 = nextPosY_536871242;
            F.line = 133;
            result_536871205[0].push(new Int32Array([x_536871215, y_536871216]));;
          };
        }
    };
  framePtr = F.prev;

  return result_536871205[0];

}

function splitDungeonParts(dungeonData_p0) {
  var result_536871265 = ({startPart: null, endPart: null, middleParts: []});

  var F = {procname: "dungeon.splitDungeonParts", prev: framePtr, filename: "D:\\tribenine\\24tribe.github.io\\src\\dungeon.nim", line: 0};
  framePtr = F;
    Label1: {
      F.line = 137;
      F.filename = "dungeon.nim";
      var dungeonpart_536871288 = null;
      F.line = 249;
      F.filename = "iterators.nim";
      var i_536871463 = 0;
      F.line = 250;
      var L_536871464 = (dungeonData_p0).length;
      Label2: {
        F.line = 251;
          Label3: while (true) {
          if (!(i_536871463 < L_536871464)) break Label3;
            F.line = 137;
            F.filename = "dungeon.nim";
            dungeonpart_536871288 = dungeonData_p0[chckIndx(i_536871463, 0, (dungeonData_p0).length - 1)];
            if ((dungeonpart_536871288.id == 101)) {
            F.line = 139;
            result_536871265.startPart = dungeonpart_536871288;
            }
            else {
            if ((dungeonpart_536871288.id == 201)) {
            F.line = 141;
            result_536871265.endPart = dungeonpart_536871288;
            }
            else {
              F.line = 143;
            result_536871265.middleParts.push(dungeonpart_536871288);;
            }
            }
            F.line = 13;
            F.filename = "iterators.nim";
            i_536871463 += 1;
            if (!(((dungeonData_p0).length == L_536871464))) {
            F.line = 254;
            failedAssertImpl__stdZassertions_u84(makeNimstrLit("C:\\Users\\aine\\.choosenim\\toolchains\\nim-2.2.4\\lib\\system\\iterators.nim(254, 11) `len(a) == L` the length of the seq changed while iterating over it"));
            }
            
          }
      };
    };
  framePtr = F.prev;

  return result_536871265;

}

function updateEntrances(entrances_p0, nodePos_p1, otherNodePos_p2) {
  var F = {procname: "dungeon.updateEntrances", prev: framePtr, filename: "D:\\tribenine\\24tribe.github.io\\src\\dungeon.nim", line: 0};
  framePtr = F;
    F.line = 147;
    F.filename = "dungeon.nim";
    var diffX_536871361 = subInt(nodePos_p1[chckIndx(0, 0, (nodePos_p1).length - 1)], otherNodePos_p2[chckIndx(0, 0, (otherNodePos_p2).length - 1)]);
    F.line = 148;
    var diffY_536871362 = subInt(nodePos_p1[chckIndx(1, 0, (nodePos_p1).length - 1)], otherNodePos_p2[chckIndx(1, 0, (otherNodePos_p2).length - 1)]);
    if ((diffX_536871361 == 1)) {
    F.line = 151;
    entrances_p0.right = 1;
    }
    else {
    if ((diffX_536871361 == (-1))) {
    F.line = 153;
    entrances_p0.left = 1;
    }
    }
    if ((diffY_536871362 == 1)) {
    F.line = 156;
    entrances_p0.bottom = 1;
    }
    else {
    if ((diffY_536871362 == (-1))) {
    F.line = 158;
    entrances_p0.top = 1;
    }
    }
  framePtr = F.prev;

  
}

function getMiddleNodesEntrances(path_p0) {
  var result_536871365 = [];

  var F = {procname: "dungeon.getMiddleNodesEntrances", prev: framePtr, filename: "D:\\tribenine\\24tribe.github.io\\src\\dungeon.nim", line: 0};
  framePtr = F;
    Label1: {
      F.line = 162;
      F.filename = "dungeon.nim";
      var i_536871373 = 0;
      F.line = 126;
      F.filename = "iterators_1.nim";
      var colontmp__536871467 = 0;
      F.line = 162;
      F.filename = "dungeon.nim";
      colontmp__536871467 = subInt((path_p0).length, 1);
      F.line = 128;
      F.filename = "iterators_1.nim";
      var i_536871468 = 1;
      Label2: {
        F.line = 129;
          Label3: while (true) {
          if (!(i_536871468 < colontmp__536871467)) break Label3;
            F.line = 162;
            F.filename = "dungeon.nim";
            i_536871373 = i_536871468;
            F.line = 163;
            var entrances_536871374 = [{top: 0, right: 0, bottom: 0, left: 0}];
            F.line = 164;
            var nodePos_536871375 = nimCopy(null, path_p0[chckIndx(i_536871373, 0, (path_p0).length - 1)], NTI536870919);
            F.line = 165;
            var lastNodePos_536871376 = nimCopy(null, path_p0[chckIndx(subInt(i_536871373, 1), 0, (path_p0).length - 1)], NTI536870919);
            F.line = 166;
            var nextNodePos_536871377 = nimCopy(null, path_p0[chckIndx(addInt(i_536871373, 1), 0, (path_p0).length - 1)], NTI536870919);
            F.line = 168;
            updateEntrances(entrances_536871374[0], lastNodePos_536871376, nodePos_536871375);
            F.line = 169;
            updateEntrances(entrances_536871374[0], nextNodePos_536871377, nodePos_536871375);
            F.line = 171;
            var Temporary4 = nimCopy(null, entrances_536871374[0], NTI536870934);
            result_536871365.push(Temporary4);;
            F.line = 131;
            F.filename = "iterators_1.nim";
            i_536871468 = addInt(i_536871468, 1);
          }
      };
    };
  framePtr = F.prev;

  return result_536871365;

}

function dungeonPartToDungeonPiece(dungeonPart_p0, cityId_p1) {
  var result_536871404 = ({x: 0, y: 0, rotate: 0, dungeonPieceId: 0});

  var F = {procname: "dungeon.dungeonPartToDungeonPiece", prev: framePtr, filename: "D:\\tribenine\\24tribe.github.io\\src\\dungeon.nim", line: 0};
  framePtr = F;
    F.line = 175;
    F.filename = "dungeon.nim";
    result_536871404 = nimCopy(result_536871404, {x: dungeonPart_p0.blocks[chckIndx(0, 0, (dungeonPart_p0.blocks).length - 1)].x, y: dungeonPart_p0.blocks[chckIndx(0, 0, (dungeonPart_p0.blocks).length - 1)].y, rotate: dungeonPart_p0.angle, dungeonPieceId: addInt(mulInt(cityId_p1, 10000), dungeonPart_p0.id)}, NTI536870932);
  framePtr = F.prev;

  return result_536871404;

}
var F = {procname: "module dungeon", prev: framePtr, filename: "D:\\tribenine\\24tribe.github.io\\src\\dungeon.nim", line: 0};
framePtr = F;
F.line = 3;
F.filename = "dungeon.nim";
randomize__pureZrandom_u299();
framePtr = F.prev;
var F = {procname: "module dungeon", prev: framePtr, filename: "D:\\tribenine\\24tribe.github.io\\src\\dungeon.nim", line: 0};
framePtr = F;
framePtr = F.prev;
